// 단어장 데이터
export const vocabulary = [
  {
    kanji: '会う',
    hiragana: 'あう',
    romaji: 'au',
    korean: '만나다',
    english: 'meet',
    partOfSpeech: 'verb',
    example: '友達に会う',
    exampleHiragana: 'ともだちにあう',
    exampleRomaji: 'tomodachi ni au',
    exampleKorean: '친구를 만나다'
  },
  {
    kanji: '青い',
    hiragana: 'あおい',
    romaji: 'aoi',
    korean: '푸른',
    english: 'blue',
    partOfSpeech: 'adjective',
    example: '青い空',
    exampleHiragana: 'あおいそら',
    exampleRomaji: 'aoi sora',
    exampleKorean: '푸른 하늘'
  },
  {
    kanji: '赤い',
    hiragana: 'あかい',
    romaji: 'akai',
    korean: '빨간',
    english: 'red',
    partOfSpeech: 'adjective',
    example: '赤い花',
    exampleHiragana: 'あかいはな',
    exampleRomaji: 'akai hana',
    exampleKorean: '빨간 꽃'
  },
  {
    kanji: '明るい',
    hiragana: 'あかるい',
    romaji: 'akarui',
    korean: '밝은',
    english: 'bright',
    partOfSpeech: 'adjective',
    example: '明るい部屋',
    exampleHiragana: 'あかるいへや',
    exampleRomaji: 'akarui heya',
    exampleKorean: '밝은 방'
  },
  {
    kanji: '秋',
    hiragana: 'あき',
    romaji: 'aki',
    korean: '가을',
    english: 'autumn',
    partOfSpeech: 'noun',
    example: '秋が好きです',
    exampleHiragana: 'あきがすきです',
    exampleRomaji: 'aki ga suki desu',
    exampleKorean: '가을을 좋아합니다'
  },
  {
    kanji: '開く',
    hiragana: 'あく',
    romaji: 'aku',
    korean: '열리다',
    english: 'to open, to become open',
    partOfSpeech: 'verb',
    example: 'ドアが開く',
    exampleHiragana: 'どあがあく',
    exampleRomaji: 'doa ga aku',
    exampleKorean: '문이 열리다'
  },
  {
    kanji: '開ける',
    hiragana: 'あける',
    romaji: 'akeru',
    korean: '열기',
    english: 'to open',
    partOfSpeech: 'verb',
    example: '窓を開ける',
    exampleHiragana: 'まどをあける',
    exampleRomaji: 'mado o akeru',
    exampleKorean: '창문을 열다'
  },
  {
    kanji: '',
    hiragana: 'あげる',
    romaji: 'ageru',
    korean: '주다',
    english: 'to give',
    partOfSpeech: 'verb',
    example: 'プレゼントをあげる',
    exampleHiragana: 'ぷれぜんとをあげる',
    exampleRomaji: 'purezento o ageru',
    exampleKorean: '선물을 주다'
  },
  {
    kanji: '朝',
    hiragana: 'あさ',
    romaji: 'asa',
    korean: '아침',
    english: 'morning',
    partOfSpeech: 'noun',
    example: '朝の散歩',
    exampleHiragana: 'あさのさんぽ',
    exampleRomaji: 'asa no sanpo',
    exampleKorean: '아침 산책'
  },
  {
    kanji: '朝ご飯',
    hiragana: 'あさごはん',
    romaji: 'asa gohan',
    korean: '아침밥',
    english: 'breakfast',
    partOfSpeech: 'noun',
    example: '朝ご飯を食べる',
    exampleHiragana: 'あさごはんをたべる',
    exampleRomaji: 'asa gohan o taberu',
    exampleKorean: '아침밥을 먹다'
  },
  {
    kanji: '明後日',
    hiragana: 'あさって',
    romaji: 'asatte',
    korean: '모레',
    english: 'day after tomorrow',
    partOfSpeech: 'noun',
    example: '明後日会いましょう',
    exampleHiragana: 'あさってあいましょう',
    exampleRomaji: 'asatte ai mashou',
    exampleKorean: '모레 만나요'
  },
  {
    kanji: '足',
    hiragana: 'あし',
    romaji: 'ashi',
    korean: '다리',
    english: 'foot, leg',
    partOfSpeech: 'noun',
    example: '足が痛い',
    exampleHiragana: 'あしがいたい',
    exampleRomaji: 'ashi ga itai',
    exampleKorean: '다리가 아프다'
  },
  {
    kanji: '明日',
    hiragana: 'あした',
    romaji: 'ashita',
    korean: '내일',
    english: 'tomorrow',
    partOfSpeech: 'noun',
    example: '明日は雨です',
    exampleHiragana: 'あしたはあめです',
    exampleRomaji: 'ashita wa ame desu',
    exampleKorean: '내일은 비입니다'
  },
  {
    kanji: '',
    hiragana: 'あそこ',
    romaji: 'asoko',
    korean: '저기',
    english: 'over there',
    partOfSpeech: 'noun',
    example: 'あそこに本があります',
    exampleHiragana: 'あそこにほんがあります',
    exampleRomaji: 'asoko ni hon ga arimasu',
    exampleKorean: '저기에 책이 있습니다'
  },
  {
    kanji: '遊ぶ',
    hiragana: 'あそぶ',
    romaji: 'asobu',
    korean: '놀다',
    english: 'to play',
    partOfSpeech: 'verb',
    example: '公園で遊ぶ',
    exampleHiragana: 'こうえんであそぶ',
    exampleRomaji: 'kouen de asobu',
    exampleKorean: '공원에서 놀다'
  },
  {
    kanji: '暖かい',
    hiragana: 'あたたかい',
    romaji: 'atatakai',
    korean: '따뜻한',
    english: 'warm',
    partOfSpeech: 'adjective',
    example: '暖かい日',
    exampleHiragana: 'あたたかいひ',
    exampleRomaji: 'atatakai hi',
    exampleKorean: '따뜻한 날'
  },
  {
    kanji: '頭',
    hiragana: 'あたま',
    romaji: 'atama',
    korean: '머리',
    english: 'head',
    partOfSpeech: 'noun',
    example: '頭が痛い',
    exampleHiragana: 'あたまがいたい',
    exampleRomaji: 'atama ga itai',
    exampleKorean: '머리가 아프다'
  },
  {
    kanji: '新しい',
    hiragana: 'あたらしい',
    romaji: 'atarashii',
    korean: '새로운',
    english: 'new',
    partOfSpeech: 'adjective',
    example: '新しい車',
    exampleHiragana: 'あたらしいくるま',
    exampleRomaji: 'atarashii kuruma',
    exampleKorean: '새로운 차'
  },
  {
    kanji: '',
    hiragana: 'あちら',
    romaji: 'achira',
    korean: '저쪽',
    english: 'there',
    partOfSpeech: 'noun',
    example: 'あちらを見てください',
    exampleHiragana: 'あちらをみてください',
    exampleRomaji: 'achira o mite kudasai',
    exampleKorean: '저쪽을 보세요'
  },
  {
    kanji: '暑い',
    hiragana: 'あつい',
    romaji: 'atsui',
    korean: '덥다',
    english: 'hot',
    partOfSpeech: 'adjective',
    example: '今日は暑いです',
    exampleHiragana: 'きょうはあついです',
    exampleRomaji: 'kyou wa atsui desu',
    exampleKorean: '오늘은 덥습니다'
  },
  {
    kanji: '熱い',
    hiragana: 'あつい',
    romaji: 'atsui',
    korean: '뜨겁다',
    english: 'hot to the touch',
    partOfSpeech: 'adjective',
    example: '熱いお茶',
    exampleHiragana: 'あついおちゃ',
    exampleRomaji: 'atsui ocha',
    exampleKorean: '뜨거운 차'
  },
  {
    kanji: '厚い',
    hiragana: 'あつい',
    romaji: 'atsui',
    korean: '두꺼운',
    english: 'thick, deep, kind',
    partOfSpeech: 'adjective',
    example: '厚い本',
    exampleHiragana: 'あついほん',
    exampleRomaji: 'atsui hon',
    exampleKorean: '두꺼운 책'
  },
  {
    kanji: '',
    hiragana: 'あっち',
    romaji: 'acchi',
    korean: '저기',
    english: 'over there',
    partOfSpeech: 'noun',
    example: 'あっちを見て',
    exampleHiragana: 'あっちをみて',
    exampleRomaji: 'acchi o mite',
    exampleKorean: '저기를 봐'
  },
  {
    kanji: '後',
    hiragana: 'あと',
    romaji: 'ato',
    korean: '나중에',
    english: 'afterwards, later',
    partOfSpeech: 'adverb',
    example: '後で会いましょう',
    exampleHiragana: 'あとであいましょう',
    exampleRomaji: 'ato de ai mashou',
    exampleKorean: '나중에 만나요'
  },
  {
    kanji: '',
    hiragana: 'あなた',
    romaji: 'anata',
    korean: '당신',
    english: 'you',
    partOfSpeech: 'pronoun',
    example: 'あなたは誰ですか',
    exampleHiragana: 'あなたはだれですか',
    exampleRomaji: 'anata wa dare desu ka',
    exampleKorean: '당신은 누구입니까'
  },
  {
    kanji: '兄',
    hiragana: 'あに',
    romaji: 'ani',
    korean: '형/오빠',
    english: 'older brother',
    partOfSpeech: 'noun',
    example: '兄が来ました',
    exampleHiragana: 'あにがきました',
    exampleRomaji: 'ani ga kimashita',
    exampleKorean: '형이 왔습니다'
  },
  {
    kanji: '姉',
    hiragana: 'あね',
    romaji: 'ane',
    korean: '누나/언니',
    english: 'older sister',
    partOfSpeech: 'noun',
    example: '姉と話す',
    exampleHiragana: 'あねとはなす',
    exampleRomaji: 'ane to hanasu',
    exampleKorean: '언니와 이야기하다'
  },
  {
    kanji: '',
    hiragana: 'あの',
    romaji: 'ano',
    korean: '그',
    english: 'that over there',
    partOfSpeech: 'adjective',
    example: 'あの本',
    exampleHiragana: 'あのほん',
    exampleRomaji: 'ano hon',
    exampleKorean: '그 책'
  },
  {
    kanji: '',
    hiragana: 'アパート',
    romaji: 'apaato',
    korean: '아파트',
    english: 'apartment',
    partOfSpeech: 'noun',
    example: 'アパートに住む',
    exampleHiragana: 'あぱーとにすむ',
    exampleRomaji: 'apaato ni sumu',
    exampleKorean: '아파트에 살다'
  },
  {
    kanji: '浴びる',
    hiragana: 'あびる',
    romaji: 'abiru',
    korean: '목욕하다',
    english: 'to bathe, to shower',
    partOfSpeech: 'verb',
    example: 'シャワーを浴びる',
    exampleHiragana: 'しゃわーをあびる',
    exampleRomaji: 'shawaa o abiru',
    exampleKorean: '샤워를 하다'
  },
  {
    kanji: '危ない',
    hiragana: 'あぶない',
    romaji: 'abunai',
    korean: '위험한',
    english: 'dangerous',
    partOfSpeech: 'adjective',
    example: '危ない道',
    exampleHiragana: 'あぶないみち',
    exampleRomaji: 'abunai michi',
    exampleKorean: '위험한 길'
  },
  {
    kanji: '甘い',
    hiragana: 'あまい',
    romaji: 'amai',
    korean: '달콤한',
    english: 'sweet',
    partOfSpeech: 'adjective',
    example: '甘いケーキ',
    exampleHiragana: 'あまいけーき',
    exampleRomaji: 'amai keeki',
    exampleKorean: '달콤한 케이크'
  },
  {
    kanji: '',
    hiragana: 'あまり',
    romaji: 'amari',
    korean: '별로',
    english: 'not very',
    partOfSpeech: 'adverb',
    example: 'あまり好きじゃない',
    exampleHiragana: 'あまりすきじゃない',
    exampleRomaji: 'amari suki ja nai',
    exampleKorean: '별로 좋아하지 않다'
  },
  {
    kanji: '雨',
    hiragana: 'あめ',
    romaji: 'ame',
    korean: '비',
    english: 'rain',
    partOfSpeech: 'noun',
    example: '雨が降る',
    exampleHiragana: 'あめがふる',
    exampleRomaji: 'ame ga furu',
    exampleKorean: '비가 오다'
  },
  {
    kanji: '飴',
    hiragana: 'あめ',
    romaji: 'ame',
    korean: '사탕',
    english: 'candy',
    partOfSpeech: 'noun',
    example: '飴を食べる',
    exampleHiragana: 'あめをたべる',
    exampleRomaji: 'ame o taberu',
    exampleKorean: '사탕을 먹다'
  },
  {
    kanji: '洗う',
    hiragana: 'あらう',
    romaji: 'arau',
    korean: '씻다',
    english: 'to wash',
    partOfSpeech: 'verb',
    example: '手を洗う',
    exampleHiragana: 'てをあらう',
    exampleRomaji: 'te o arau',
    exampleKorean: '손을 씻다'
  },
  {
    kanji: '',
    hiragana: 'ある',
    romaji: 'aru',
    korean: '있다',
    english: 'to be, to have (inanimate objects)',
    partOfSpeech: 'verb',
    example: '本がある',
    exampleHiragana: 'ほんがある',
    exampleRomaji: 'hon ga aru',
    exampleKorean: '책이 있다'
  },
  {
    kanji: '歩く',
    hiragana: 'あるく',
    romaji: 'aruku',
    korean: '걷다',
    english: 'to walk',
    partOfSpeech: 'verb',
    example: '公園を歩く',
    exampleHiragana: 'こうえんをあるく',
    exampleRomaji: 'kouen o aruku',
    exampleKorean: '공원을 걷다'
  },
  {
    kanji: '',
    hiragana: 'あれ',
    romaji: 'are',
    korean: '그것',
    english: 'that',
    partOfSpeech: 'pronoun',
    example: 'あれは何ですか',
    exampleHiragana: 'あれはなんですか',
    exampleRomaji: 'are wa nan desu ka',
    exampleKorean: '그것은 무엇입니까'
  },
  {
    kanji: '',
    hiragana: 'いい',
    romaji: 'ii',
    korean: '좋은',
    english: 'good',
    partOfSpeech: 'adjective',
    example: 'いい天気',
    exampleHiragana: 'いいてんき',
    exampleRomaji: 'ii tenki',
    exampleKorean: '좋은 날씨'
  },
  {
    kanji: '',
    hiragana: 'いいえ',
    romaji: 'iie',
    korean: '아니오',
    english: 'no',
    partOfSpeech: 'interjection',
    example: 'いいえ、違います',
    exampleHiragana: 'いいえ、ちがいます',
    exampleRomaji: 'iie, chigaimasu',
    exampleKorean: '아니오, 틀렸습니다'
  },
  {
    kanji: '言う',
    hiragana: 'いう',
    romaji: 'iu',
    korean: '말하다',
    english: 'to say',
    partOfSpeech: 'verb',
    example: 'ありがとうと言う',
    exampleHiragana: 'ありがとうという',
    exampleRomaji: 'arigatou to iu',
    exampleKorean: '고맙다고 말하다'
  },
  {
    kanji: '家',
    hiragana: 'いえ',
    romaji: 'ie',
    korean: '집',
    english: 'house',
    partOfSpeech: 'noun',
    example: '家に帰る',
    exampleHiragana: 'いえにかえる',
    exampleRomaji: 'ie ni kaeru',
    exampleKorean: '집에 돌아가다'
  },
  {
    kanji: '',
    hiragana: 'いかが',
    romaji: 'ikaga',
    korean: '어떻게',
    english: 'how',
    partOfSpeech: 'adverb',
    example: 'いかがですか',
    exampleHiragana: 'いかがですか',
    exampleRomaji: 'ikaga desu ka',
    exampleKorean: '어떠십니까'
  },
  {
    kanji: '行く',
    hiragana: 'いく',
    romaji: 'iku',
    korean: '가다',
    english: 'to go',
    partOfSpeech: 'verb',
    example: '学校に行く',
    exampleHiragana: 'がっこうにいく',
    exampleRomaji: 'gakkou ni iku',
    exampleKorean: '학교에 가다'
  },
  {
    kanji: '',
    hiragana: 'いくつ',
    romaji: 'ikutsu',
    korean: '몇',
    english: 'how many, how old',
    partOfSpeech: 'pronoun',
    example: 'いくつありますか',
    exampleHiragana: 'いくつありますか',
    exampleRomaji: 'ikutsu arimasu ka',
    exampleKorean: '몇 개 있습니까'
  },
  {
    kanji: '',
    hiragana: 'いくら',
    romaji: 'ikura',
    korean: '얼마',
    english: 'how much',
    partOfSpeech: 'pronoun',
    example: 'いくらですか',
    exampleHiragana: 'いくらですか',
    exampleRomaji: 'ikura desu ka',
    exampleKorean: '얼마입니까'
  },
  {
    kanji: '池',
    hiragana: 'いけ',
    romaji: 'ike',
    korean: '연못',
    english: 'pond',
    partOfSpeech: 'noun',
    example: '池の魚',
    exampleHiragana: 'いけのさかな',
    exampleRomaji: 'ike no sakana',
    exampleKorean: '연못의 물고기'
  },
  {
    kanji: '医者',
    hiragana: 'いしゃ',
    romaji: 'isha',
    korean: '의사',
    english: 'medical doctor',
    partOfSpeech: 'noun',
    example: '医者に診てもらう',
    exampleHiragana: 'いしゃにみてもらう',
    exampleRomaji: 'isha ni mite morau',
    exampleKorean: '의사에게 진찰받다'
  },
  {
    kanji: '椅子',
    hiragana: 'いす',
    romaji: 'isu',
    korean: '의자',
    english: 'chair',
    partOfSpeech: 'noun',
    example: '椅子に座る',
    exampleHiragana: 'いすにすわる',
    exampleRomaji: 'isu ni suwaru',
    exampleKorean: '의자에 앉다'
  },
  {
    kanji: '忙しい',
    hiragana: 'いそがしい',
    romaji: 'isogashii',
    korean: '바쁜',
    english: 'busy',
    partOfSpeech: 'adjective',
    example: '忙しい日',
    exampleHiragana: 'いそがしいひ',
    exampleRomaji: 'isogashii hi',
    exampleKorean: '바쁜 날'
  },
  {
    kanji: '痛い',
    hiragana: 'いたい',
    romaji: 'itai',
    korean: '아픈',
    english: 'painful',
    partOfSpeech: 'adjective',
    example: '頭が痛い',
    exampleHiragana: 'あたまがいたい',
    exampleRomaji: 'atama ga itai',
    exampleKorean: '머리가 아프다'
  },
  {
    kanji: '一日',
    hiragana: 'いちにち',
    romaji: 'ichinichi',
    korean: '하루',
    english: 'first of the month, one day',
    partOfSpeech: 'noun',
    example: '一日目',
    exampleHiragana: 'いちにちめ',
    exampleRomaji: 'ichinichi me',
    exampleKorean: '첫날'
  },
  {
    kanji: '',
    hiragana: 'いちばん',
    romaji: 'ichiban',
    korean: '가장',
    english: 'best, first',
    partOfSpeech: 'adverb',
    example: 'いちばん好き',
    exampleHiragana: 'いちばんすき',
    exampleRomaji: 'ichiban suki',
    exampleKorean: '가장 좋아하는'
  },
  {
    kanji: '',
    hiragana: 'いつ',
    romaji: 'itsu',
    korean: '언제',
    english: 'when',
    partOfSpeech: 'pronoun',
    example: 'いつ来ますか',
    exampleHiragana: 'いつきますか',
    exampleRomaji: 'itsu kimasu ka',
    exampleKorean: '언제 옵니까'
  },
  {
    kanji: '五日',
    hiragana: 'いつか',
    romaji: 'itsuka',
    korean: '5일',
    english: 'five days, fifth day',
    partOfSpeech: 'noun',
    example: '五日目',
    exampleHiragana: 'いつかめ',
    exampleRomaji: 'itsuka me',
    exampleKorean: '5일째'
  },
  {
    kanji: '一緒',
    hiragana: 'いっしょ',
    romaji: 'issho',
    korean: '함께',
    english: 'together',
    partOfSpeech: 'adverb',
    example: '一緒に行く',
    exampleHiragana: 'いっしょにいく',
    exampleRomaji: 'issho ni iku',
    exampleKorean: '함께 가다'
  },
  {
    kanji: '五つ',
    hiragana: 'いつつ',
    romaji: 'itsutsu',
    korean: '다섯',
    english: 'five',
    partOfSpeech: 'number',
    example: '五つのりんご',
    exampleHiragana: 'いつつのりんご',
    exampleRomaji: 'itsutsu no ringo',
    exampleKorean: '다섯 개의 사과'
  },
  {
    kanji: '',
    hiragana: 'いつも',
    romaji: 'itsumo',
    korean: '항상',
    english: 'always',
    partOfSpeech: 'adverb',
    example: 'いつもありがとう',
    exampleHiragana: 'いつもありがとう',
    exampleRomaji: 'itsumo arigatou',
    exampleKorean: '항상 고맙습니다'
  },
  {
    kanji: '犬',
    hiragana: 'いぬ',
    romaji: 'inu',
    korean: '개',
    english: 'dog',
    partOfSpeech: 'noun',
    example: '犬を飼う',
    exampleHiragana: 'いぬをかう',
    exampleRomaji: 'inu o kau',
    exampleKorean: '개를 기르다'
  },
  {
    kanji: '今',
    hiragana: 'いま',
    romaji: 'ima',
    korean: '지금',
    english: 'now',
    partOfSpeech: 'adverb',
    example: '今何時ですか',
    exampleHiragana: 'いまなんじですか',
    exampleRomaji: 'ima nanji desu ka',
    exampleKorean: '지금 몇 시입니까'
  },
  {
    kanji: '意味',
    hiragana: 'いみ',
    romaji: 'imi',
    korean: '의미',
    english: 'meaning',
    partOfSpeech: 'noun',
    example: '言葉の意味',
    exampleHiragana: 'ことばのいみ',
    exampleRomaji: 'kotoba no imi',
    exampleKorean: '단어의 의미'
  },
  {
    kanji: '妹',
    hiragana: 'いもうと',
    romaji: 'imouto',
    korean: '여동생',
    english: 'younger sister',
    partOfSpeech: 'noun',
    example: '妹がいる',
    exampleHiragana: 'いもうとがいる',
    exampleRomaji: 'imouto ga iru',
    exampleKorean: '여동생이 있다'
  },
  {
    kanji: '',
    hiragana: 'いや',
    romaji: 'iya',
    korean: '싫은',
    english: 'unpleasant, no',
    partOfSpeech: 'adjective',
    example: 'いやな天気',
    exampleHiragana: 'いやなてんき',
    exampleRomaji: 'iya na tenki',
    exampleKorean: '싫은 날씨'
  },
  {
    kanji: '入口',
    hiragana: 'いりぐち',
    romaji: 'iriguchi',
    korean: '입구',
    english: 'entrance',
    partOfSpeech: 'noun',
    example: '入口はこちら',
    exampleHiragana: 'いりぐちはこちら',
    exampleRomaji: 'iriguchi wa kochira',
    exampleKorean: '입구는 이쪽입니다'
  },
  {
    kanji: '居る',
    hiragana: 'いる',
    romaji: 'iru',
    korean: '있다',
    english: 'to be, to have (animate objects)',
    partOfSpeech: 'verb',
    example: '猫がいる',
    exampleHiragana: 'ねこがいる',
    exampleRomaji: 'neko ga iru',
    exampleKorean: '고양이가 있다'
  },
  {
    kanji: '要る',
    hiragana: 'いる',
    romaji: 'iru',
    korean: '필요하다',
    english: 'to need',
    partOfSpeech: 'verb',
    example: 'お金が要る',
    exampleHiragana: 'おかねがいる',
    exampleRomaji: 'okane ga iru',
    exampleKorean: '돈이 필요하다'
  },
  {
    kanji: '入れる',
    hiragana: 'いれる',
    romaji: 'ireru',
    korean: '넣다',
    english: 'to put in',
    partOfSpeech: 'verb',
    example: '箱に入れる',
    exampleHiragana: 'はこにいれる',
    exampleRomaji: 'hako ni ireru',
    exampleKorean: '상자에 넣다'
  },
  {
    kanji: '色',
    hiragana: 'いろ',
    romaji: 'iro',
    korean: '색',
    english: 'colour',
    partOfSpeech: 'noun',
    example: '色を選ぶ',
    exampleHiragana: 'いろをえらぶ',
    exampleRomaji: 'iro o erabu',
    exampleKorean: '색을 선택하다'
  },
  {
    kanji: '',
    hiragana: 'いろいろ',
    romaji: 'iroiro',
    korean: '여러가지',
    english: 'various',
    partOfSpeech: 'adjective',
    example: 'いろいろな本',
    exampleHiragana: 'いろいろなほん',
    exampleRomaji: 'iroiro na hon',
    exampleKorean: '여러가지 책'
  },
  {
    kanji: '上',
    hiragana: 'うえ',
    romaji: 'ue',
    korean: '위',
    english: 'on top of, above',
    partOfSpeech: 'noun',
    example: '机の上',
    exampleHiragana: 'つくえのうえ',
    exampleRomaji: 'tsukue no ue',
    exampleKorean: '책상 위'
  },
  {
    kanji: '後ろ',
    hiragana: 'うしろ',
    romaji: 'ushiro',
    korean: '뒤',
    english: 'behind',
    partOfSpeech: 'noun',
    example: '後ろを見る',
    exampleHiragana: 'うしろをみる',
    exampleRomaji: 'ushiro o miru',
    exampleKorean: '뒤를 보다'
  },
  {
    kanji: '薄い',
    hiragana: 'うすい',
    romaji: 'usui',
    korean: '얇은',
    english: 'thin, weak',
    partOfSpeech: 'adjective',
    example: '薄い紙',
    exampleHiragana: 'うすいかみ',
    exampleRomaji: 'usui kami',
    exampleKorean: '얇은 종이'
  },
  {
    kanji: '歌',
    hiragana: 'うた',
    romaji: 'uta',
    korean: '노래',
    english: 'song',
    partOfSpeech: 'noun',
    example: '歌を歌う',
    exampleHiragana: 'うたをうたう',
    exampleRomaji: 'uta o utau',
    exampleKorean: '노래를 부르다'
  },
  {
    kanji: '歌う',
    hiragana: 'うたう',
    romaji: 'utau',
    korean: '노래하다',
    english: 'to sing',
    partOfSpeech: 'verb',
    example: '歌を歌う',
    exampleHiragana: 'うたをうたう',
    exampleRomaji: 'uta o utau',
    exampleKorean: '노래를 부르다'
  },
  {
    kanji: '生まれる',
    hiragana: 'うまれる',
    romaji: 'umareru',
    korean: '태어나다',
    english: 'to be born',
    partOfSpeech: 'verb',
    example: '赤ちゃんが生まれる',
    exampleHiragana: 'あかちゃんがうまれる',
    exampleRomaji: 'akachan ga umareru',
    exampleKorean: '아기가 태어나다'
  },
  {
    kanji: '海',
    hiragana: 'うみ',
    romaji: 'umi',
    korean: '바다',
    english: 'sea',
    partOfSpeech: 'noun',
    example: '海に行く',
    exampleHiragana: 'うみにいく',
    exampleRomaji: 'umi ni iku',
    exampleKorean: '바다에 가다'
  },
  {
    kanji: '売る',
    hiragana: 'うる',
    romaji: 'uru',
    korean: '팔다',
    english: 'to sell',
    partOfSpeech: 'verb',
    example: '本を売る',
    exampleHiragana: 'ほんをうる',
    exampleRomaji: 'hon o uru',
    exampleKorean: '책을 팔다'
  },
  {
    kanji: '',
    hiragana: 'うるさい',
    romaji: 'urusai',
    korean: '시끄러운',
    english: 'noisy, annoying',
    partOfSpeech: 'adjective',
    example: 'うるさい音',
    exampleHiragana: 'うるさいおと',
    exampleRomaji: 'urusai oto',
    exampleKorean: '시끄러운 소리'
  },
  {
    kanji: '上着',
    hiragana: 'うわぎ',
    romaji: 'uwagi',
    korean: '겉옷',
    english: 'jacket',
    partOfSpeech: 'noun',
    example: '上着を着る',
    exampleHiragana: 'うわぎをきる',
    exampleRomaji: 'uwagi o kiru',
    exampleKorean: '겉옷을 입다'
  },
  {
    kanji: '絵',
    hiragana: 'え',
    romaji: 'e',
    korean: '그림',
    english: 'picture',
    partOfSpeech: 'noun',
    example: '絵を描く',
    exampleHiragana: 'えをかく',
    exampleRomaji: 'e o kaku',
    exampleKorean: '그림을 그리다'
  },
  {
    kanji: '映画',
    hiragana: 'えいが',
    romaji: 'eiga',
    korean: '영화',
    english: 'movie',
    partOfSpeech: 'noun',
    example: '映画を見る',
    exampleHiragana: 'えいがをみる',
    exampleRomaji: 'eiga o miru',
    exampleKorean: '영화를 보다'
  },
  {
    kanji: '映画館',
    hiragana: 'えいがかん',
    romaji: 'eigakan',
    korean: '영화관',
    english: 'cinema',
    partOfSpeech: 'noun',
    example: '映画館に行く',
    exampleHiragana: 'えいがかんにいく',
    exampleRomaji: 'eigakan ni iku',
    exampleKorean: '영화관에 가다'
  },
  {
    kanji: '英語',
    hiragana: 'えいご',
    romaji: 'eigo',
    korean: '영어',
    english: 'English language',
    partOfSpeech: 'noun',
    example: '英語を勉強する',
    exampleHiragana: 'えいごをべんきょうする',
    exampleRomaji: 'eigo o benkyou suru',
    exampleKorean: '영어를 공부하다'
  },
  {
    kanji: '',
    hiragana: 'ええ',
    romaji: 'ee',
    korean: '예',
    english: 'yes',
    partOfSpeech: 'interjection',
    example: 'ええ、そうです',
    exampleHiragana: 'ええ、そうです',
    exampleRomaji: 'ee, sou desu',
    exampleKorean: '예, 그렇습니다'
  },
  {
    kanji: '駅',
    hiragana: 'えき',
    romaji: 'eki',
    korean: '역',
    english: 'station',
    partOfSpeech: 'noun',
    example: '駅に着く',
    exampleHiragana: 'えきにつく',
    exampleRomaji: 'eki ni tsuku',
    exampleKorean: '역에 도착하다'
  },
  {
    kanji: '',
    hiragana: 'エレベーター',
    romaji: 'erebeetaa',
    korean: '엘리베이터',
    english: 'elevator',
    partOfSpeech: 'noun',
    example: 'エレベーターに乗る',
    exampleHiragana: 'えれべーたーにのる',
    exampleRomaji: 'erebeetaa ni noru',
    exampleKorean: '엘리베이터를 타다'
  },
  {
    kanji: '鉛筆',
    hiragana: 'えんぴつ',
    romaji: 'enpitsu',
    korean: '연필',
    english: 'pencil',
    partOfSpeech: 'noun',
    example: '鉛筆で書く',
    exampleHiragana: 'えんぴつでかく',
    exampleRomaji: 'enpitsu de kaku',
    exampleKorean: '연필로 쓰다'
  },
  {
    kanji: '',
    hiragana: 'おいしい',
    romaji: 'oishii',
    korean: '맛있는',
    english: 'delicious',
    partOfSpeech: 'adjective',
    example: 'おいしい料理',
    exampleHiragana: 'おいしいりょうり',
    exampleRomaji: 'oishii ryouri',
    exampleKorean: '맛있는 요리'
  },
  {
    kanji: '多い',
    hiragana: 'おおい',
    romaji: 'ooi',
    korean: '많은',
    english: 'many',
    partOfSpeech: 'adjective',
    example: '人が多い',
    exampleHiragana: 'ひとがおおい',
    exampleRomaji: 'hito ga ooi',
    exampleKorean: '사람이 많다'
  },
  {
    kanji: '大きい',
    hiragana: 'おおきい',
    romaji: 'ookii',
    korean: '큰',
    english: 'big',
    partOfSpeech: 'adjective',
    example: '大きい家',
    exampleHiragana: 'おおきいいえ',
    exampleRomaji: 'ookii ie',
    exampleKorean: '큰 집'
  },
  {
    kanji: '大きな',
    hiragana: 'おおきな',
    romaji: 'ookina',
    korean: '큰',
    english: 'big',
    partOfSpeech: 'adjective',
    example: '大きな木',
    exampleHiragana: 'おおきなき',
    exampleRomaji: 'ookina ki',
    exampleKorean: '큰 나무'
  },
  {
    kanji: '大勢',
    hiragana: 'おおぜい',
    romaji: 'oozei',
    korean: '많은 사람',
    english: 'great number of people',
    partOfSpeech: 'noun',
    example: '大勢の人が来た',
    exampleHiragana: 'おおぜいのひとがきた',
    exampleRomaji: 'oozei no hito ga kita',
    exampleKorean: '많은 사람이 왔다'
  },
  {
    kanji: '',
    hiragana: 'おかあさん',
    romaji: 'okaasan',
    korean: '엄마',
    english: 'mother',
    partOfSpeech: 'noun',
    example: 'おかあさんがよぶ',
    exampleHiragana: 'おかあさんがよぶ',
    exampleRomaji: 'okaasan ga yobu',
    exampleKorean: '엄마가 부른다'
  },
  {
    kanji: '',
    hiragana: 'おかし',
    romaji: 'okashi',
    korean: '과자',
    english: 'sweets, candy',
    partOfSpeech: 'noun',
    example: 'おかしをたべる',
    exampleHiragana: 'おかしをたべる',
    exampleRomaji: 'okashi o taberu',
    exampleKorean: '과자를 먹다'
  },
  {
    kanji: '',
    hiragana: 'おかね',
    romaji: 'okane',
    korean: '돈',
    english: 'money',
    partOfSpeech: 'noun',
    example: 'おかねをはらう',
    exampleHiragana: 'おかねをはらう',
    exampleRomaji: 'okane o harau',
    exampleKorean: '돈을 지불하다'
  },
  {
    kanji: '起きる',
    hiragana: 'おきる',
    romaji: 'okiru',
    korean: '일어나다',
    english: 'to get up',
    partOfSpeech: 'verb',
    example: '朝早く起きる',
    exampleHiragana: 'あさはやくおきる',
    exampleRomaji: 'asa hayaku okiru',
    exampleKorean: '아침 일찍 일어나다'
  }
]

// 배열을 랜덤하게 섞는 함수
export const shuffleArray = (array) => {
  const shuffled = [...array]
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }
  return shuffled
}

