// 단어장 데이터
export const vocabulary = [
  {
    kanji: '会う',
    hiragana: 'あう',
    romaji: 'au',
    korean: '만나다',
    english: 'meet',
    partOfSpeech: 'verb',
    example: '友達に会う',
    exampleRuby: [{ '友達': 'ともだち' }, { '会': 'あ' }],
    exampleKorean: '친구를 만나다'
  },
  {
    kanji: '青い',
    hiragana: 'あおい',
    romaji: 'aoi',
    korean: '푸른',
    english: 'blue',
    partOfSpeech: 'adjective',
    example: '青い空',
    exampleRuby: [{ '青': 'あお' }, { '空': 'そら' }],
    exampleKorean: '푸른 하늘'
  },
  {
    kanji: '赤い',
    hiragana: 'あかい',
    romaji: 'akai',
    korean: '빨간',
    english: 'red',
    partOfSpeech: 'adjective',
    example: '赤い花',
    exampleRuby: [{ 赤: 'あか' }, { 花: 'はな' }],
    exampleKorean: '빨간 꽃'
  },
  {
    kanji: '明るい',
    hiragana: 'あかるい',
    romaji: 'akarui',
    korean: '밝은',
    english: 'bright',
    partOfSpeech: 'adjective',
    example: '明るい部屋',
    exampleRuby: [{ 明: 'あか' }, { 部屋: 'へや' }],
    exampleKorean: '밝은 방'
  },
  {
    kanji: '秋',
    hiragana: 'あき',
    romaji: 'aki',
    korean: '가을',
    english: 'autumn',
    partOfSpeech: 'noun',
    example: '秋が好きです',
    exampleRuby: [{ 秋: 'あき' }, { 好: 'す' }],
    exampleKorean: '가을을 좋아합니다'
  },
  {
    kanji: '開く',
    hiragana: 'あく',
    romaji: 'aku',
    korean: '열리다',
    english: 'to open, to become open',
    partOfSpeech: 'verb',
    example: 'ドアが開く',
    exampleRuby: [{ 開: 'あ' }],
    exampleKorean: '문이 열리다'
  },
  {
    kanji: '開ける',
    hiragana: 'あける',
    romaji: 'akeru',
    korean: '열기',
    english: 'to open',
    partOfSpeech: 'verb',
    example: '窓を開ける',
    exampleRuby: [{ 窓: 'まど' }, { 開: 'あ' }],
    exampleKorean: '창문을 열다'
  },
  {
    kanji: '',
    hiragana: 'あげる',
    romaji: 'ageru',
    korean: '주다',
    english: 'to give',
    partOfSpeech: 'verb',
    example: 'プレゼントをあげる',
    exampleRuby: [],
    exampleKorean: '선물을 주다'
  },
  {
    kanji: '朝',
    hiragana: 'あさ',
    romaji: 'asa',
    korean: '아침',
    english: 'morning',
    partOfSpeech: 'noun',
    example: '朝の散歩',
    exampleRuby: [{ 朝: 'あさ' }, { 散歩: 'さんぽ' }],
    exampleKorean: '아침 산책'
  },
  {
    kanji: '朝ご飯',
    hiragana: 'あさごはん',
    romaji: 'asa gohan',
    korean: '아침밥',
    english: 'breakfast',
    partOfSpeech: 'noun',
    example: '朝ご飯を食べる',
    exampleRuby: [{ 朝: 'あさ' }, { 飯: 'はん' }, { 食: 'た' }],
    exampleKorean: '아침밥을 먹다'
  },
  {
    kanji: '明後日',
    hiragana: 'あさって',
    romaji: 'asatte',
    korean: '모레',
    english: 'day after tomorrow',
    partOfSpeech: 'noun',
    example: '明後日会いましょう',
    exampleRuby: [{ 明後日: 'あさって' }, { 会: 'あ' }],
    exampleKorean: '모레 만나요'
  },
  {
    kanji: '足',
    hiragana: 'あし',
    romaji: 'ashi',
    korean: '다리',
    english: 'foot, leg',
    partOfSpeech: 'noun',
    example: '足が痛い',
    exampleRuby: [{ 足: 'あし' }, { 痛: 'いた' }],
    exampleKorean: '다리가 아프다'
  },
  {
    kanji: '明日',
    hiragana: 'あした',
    romaji: 'ashita',
    korean: '내일',
    english: 'tomorrow',
    partOfSpeech: 'noun',
    example: '明日は雨です',
    exampleRuby: [{ 明日: 'あした' }, { 雨: 'あめ' }],
    exampleKorean: '내일은 비입니다'
  },
  {
    kanji: '',
    hiragana: 'あそこ',
    romaji: 'asoko',
    korean: '저기',
    english: 'over there',
    partOfSpeech: 'noun',
    example: 'あそこに本があります',
    exampleRuby: [{ 本: 'ほん' }],
    exampleKorean: '저기에 책이 있습니다'
  },
  {
    kanji: '遊ぶ',
    hiragana: 'あそぶ',
    romaji: 'asobu',
    korean: '놀다',
    english: 'to play',
    partOfSpeech: 'verb',
    example: '公園で遊ぶ',
    exampleRuby: [{ 公園: 'こうえん' }, { 遊: 'あそ' }],
    exampleKorean: '공원에서 놀다'
  },
  {
    kanji: '暖かい',
    hiragana: 'あたたかい',
    romaji: 'atatakai',
    korean: '따뜻한',
    english: 'warm',
    partOfSpeech: 'adjective',
    example: '暖かい日',
    exampleRuby: [{ 暖: 'あたた' }, { 日: 'ひ' }],
    exampleKorean: '따뜻한 날'
  },
  {
    kanji: '頭',
    hiragana: 'あたま',
    romaji: 'atama',
    korean: '머리',
    english: 'head',
    partOfSpeech: 'noun',
    example: '頭が痛い',
    exampleRuby: [{ 頭: 'あたま' }, { 痛: 'いた' }],
    exampleKorean: '머리가 아프다'
  },
  {
    kanji: '新しい',
    hiragana: 'あたらしい',
    romaji: 'atarashii',
    korean: '새로운',
    english: 'new',
    partOfSpeech: 'adjective',
    example: '新しい車',
    exampleRuby: [{ 新: 'あたら' }, { 車: 'くるま' }],
    exampleKorean: '새로운 차'
  },
  {
    kanji: '',
    hiragana: 'あちら',
    romaji: 'achira',
    korean: '저쪽',
    english: 'there',
    partOfSpeech: 'noun',
    example: 'あちらを見てください',
    exampleRuby: [{ 見: 'み' }],
    exampleKorean: '저쪽을 보세요'
  },
  {
    kanji: '暑い',
    hiragana: 'あつい',
    romaji: 'atsui',
    korean: '덥다',
    english: 'hot',
    partOfSpeech: 'adjective',
    example: '今日は暑いです',
    exampleRuby: [{ 今日: 'きょう' }, { 暑: 'あつ' }],
    exampleKorean: '오늘은 덥습니다'
  },
  {
    kanji: '熱い',
    hiragana: 'あつい',
    romaji: 'atsui',
    korean: '뜨겁다',
    english: 'hot to the touch',
    partOfSpeech: 'adjective',
    example: '熱いお茶',
    exampleRuby: [{ 熱: 'あつ' }, { 茶: 'ちゃ' }],
    exampleKorean: '뜨거운 차'
  },
  {
    kanji: '厚い',
    hiragana: 'あつい',
    romaji: 'atsui',
    korean: '두꺼운',
    english: 'thick, deep, kind',
    partOfSpeech: 'adjective',
    example: '厚い本',
    exampleRuby: [{ 厚: 'あつ' }, { 本: 'ほん' }],
    exampleKorean: '두꺼운 책'
  },
  {
    kanji: '',
    hiragana: 'あっち',
    romaji: 'acchi',
    korean: '저기',
    english: 'over there',
    partOfSpeech: 'noun',
    example: 'あっちを見て',
    exampleRuby: [{ 見: 'み' }],
    exampleKorean: '저기를 봐'
  },
  {
    kanji: '後',
    hiragana: 'あと',
    romaji: 'ato',
    korean: '나중에',
    english: 'afterwards, later',
    partOfSpeech: 'adverb',
    example: '後で会いましょう',
    exampleRuby: [{ 後: 'あと' }, { 会: 'あ' }],
    exampleKorean: '나중에 만나요'
  },
  {
    kanji: '',
    hiragana: 'あなた',
    romaji: 'anata',
    korean: '당신',
    english: 'you',
    partOfSpeech: 'pronoun',
    example: 'あなたは誰ですか',
    exampleRuby: [{ 誰: 'だれ' }],
    exampleKorean: '당신은 누구입니까'
  },
  {
    kanji: '兄',
    hiragana: 'あに',
    romaji: 'ani',
    korean: '형/오빠',
    english: 'older brother',
    partOfSpeech: 'noun',
    example: '兄が来ました',
    exampleRuby: [{ 兄: 'あに' }, { 来: 'き' }],
    exampleKorean: '형이 왔습니다'
  },
  {
    kanji: '姉',
    hiragana: 'あね',
    romaji: 'ane',
    korean: '누나/언니',
    english: 'older sister',
    partOfSpeech: 'noun',
    example: '姉と話す',
    exampleRuby: [{ 姉: 'あね' }, { 話: 'はな' }],
    exampleKorean: '언니와 이야기하다'
  },
  {
    kanji: '',
    hiragana: 'あの',
    romaji: 'ano',
    korean: '그',
    english: 'that over there',
    partOfSpeech: 'adjective',
    example: 'あの本',
    exampleRuby: [{ 本: 'ほん' }],
    exampleKorean: '그 책'
  },
  {
    kanji: '',
    hiragana: 'アパート',
    romaji: 'apaato',
    korean: '아파트',
    english: 'apartment',
    partOfSpeech: 'noun',
    example: 'アパートに住む',
    exampleRuby: [{ 住: 'す' }],
    exampleKorean: '아파트에 살다'
  },
  {
    kanji: '浴びる',
    hiragana: 'あびる',
    romaji: 'abiru',
    korean: '목욕하다',
    english: 'to bathe, to shower',
    partOfSpeech: 'verb',
    example: 'シャワーを浴びる',
    exampleRuby: [{ 浴: 'あ' }],
    exampleKorean: '샤워를 하다'
  },
  {
    kanji: '危ない',
    hiragana: 'あぶない',
    romaji: 'abunai',
    korean: '위험한',
    english: 'dangerous',
    partOfSpeech: 'adjective',
    example: '危ない道',
    exampleRuby: [{ 危: 'あぶ' }, { 道: 'みち' }],
    exampleKorean: '위험한 길'
  },
  {
    kanji: '甘い',
    hiragana: 'あまい',
    romaji: 'amai',
    korean: '달콤한',
    english: 'sweet',
    partOfSpeech: 'adjective',
    example: '甘いケーキ',
    exampleRuby: [{ 甘: 'あま' }],
    exampleKorean: '달콤한 케이크'
  },
  {
    kanji: '',
    hiragana: 'あまり',
    romaji: 'amari',
    korean: '별로',
    english: 'not very',
    partOfSpeech: 'adverb',
    example: 'あまり好きじゃない',
    exampleRuby: [{ 好: 'す' }],
    exampleKorean: '별로 좋아하지 않다'
  },
  {
    kanji: '雨',
    hiragana: 'あめ',
    romaji: 'ame',
    korean: '비',
    english: 'rain',
    partOfSpeech: 'noun',
    example: '雨が降る',
    exampleRuby: [{ 雨: 'あめ' }, { 降: 'ふ' }],
    exampleKorean: '비가 오다'
  },
  {
    kanji: '飴',
    hiragana: 'あめ',
    romaji: 'ame',
    korean: '사탕',
    english: 'candy',
    partOfSpeech: 'noun',
    example: '飴を食べる',
    exampleRuby: [{ 飴: 'あめ' }, { 食: 'た' }],
    exampleKorean: '사탕을 먹다'
  },
  {
    kanji: '洗う',
    hiragana: 'あらう',
    romaji: 'arau',
    korean: '씻다',
    english: 'to wash',
    partOfSpeech: 'verb',
    example: '手を洗う',
    exampleRuby: [{ 手: 'て' }, { 洗: 'あら' }],
    exampleKorean: '손을 씻다'
  },
  {
    kanji: '',
    hiragana: 'ある',
    romaji: 'aru',
    korean: '있다',
    english: 'to be, to have (inanimate objects)',
    partOfSpeech: 'verb',
    example: '本がある',
    exampleRuby: [{ 本: 'ほん' }],
    exampleKorean: '책이 있다'
  },
  {
    kanji: '歩く',
    hiragana: 'あるく',
    romaji: 'aruku',
    korean: '걷다',
    english: 'to walk',
    partOfSpeech: 'verb',
    example: '公園を歩く',
    exampleRuby: [{ 公園: 'こうえん' }, { 歩: 'ある' }],
    exampleKorean: '공원을 걷다'
  },
  {
    kanji: '',
    hiragana: 'あれ',
    romaji: 'are',
    korean: '그것',
    english: 'that',
    partOfSpeech: 'pronoun',
    example: 'あれは何ですか',
    exampleRuby: [{ 何: 'なん' }],
    exampleKorean: '그것은 무엇입니까'
  },
  {
    kanji: '',
    hiragana: 'いい',
    romaji: 'ii',
    korean: '좋은',
    english: 'good',
    partOfSpeech: 'adjective',
    example: 'いい天気',
    exampleRuby: [{ 天気: 'てんき' }],
    exampleKorean: '좋은 날씨'
  },
  {
    kanji: '',
    hiragana: 'いいえ',
    romaji: 'iie',
    korean: '아니오',
    english: 'no',
    partOfSpeech: 'interjection',
    example: 'いいえ、違います',
    exampleRuby: [{ 違: 'ちが' }],
    exampleKorean: '아니오, 틀렸습니다'
  },
  {
    kanji: '言う',
    hiragana: 'いう',
    romaji: 'iu',
    korean: '말하다',
    english: 'to say',
    partOfSpeech: 'verb',
    example: 'ありがとうと言う',
    exampleRuby: [{ 言: 'い' }],
    exampleKorean: '고맙다고 말하다'
  },
  {
    kanji: '家',
    hiragana: 'いえ',
    romaji: 'ie',
    korean: '집',
    english: 'house',
    partOfSpeech: 'noun',
    example: '家に帰る',
    exampleRuby: [{ 家: 'いえ' }, { 帰: 'かえ' }],
    exampleKorean: '집에 돌아가다'
  },
  {
    kanji: '',
    hiragana: 'いかが',
    romaji: 'ikaga',
    korean: '어떻게',
    english: 'how',
    partOfSpeech: 'adverb',
    example: 'いかがですか',
    exampleRuby: [],
    exampleKorean: '어떠십니까'
  },
  {
    kanji: '行く',
    hiragana: 'いく',
    romaji: 'iku',
    korean: '가다',
    english: 'to go',
    partOfSpeech: 'verb',
    example: '学校に行く',
    exampleRuby: [{ 学校: 'がっこう' }, { 行: 'い' }],
    exampleKorean: '학교에 가다'
  },
  {
    kanji: '',
    hiragana: 'いくつ',
    romaji: 'ikutsu',
    korean: '몇',
    english: 'how many, how old',
    partOfSpeech: 'pronoun',
    example: 'いくつありますか',
    exampleRuby: [],
    exampleKorean: '몇 개 있습니까'
  },
  {
    kanji: '',
    hiragana: 'いくら',
    romaji: 'ikura',
    korean: '얼마',
    english: 'how much',
    partOfSpeech: 'pronoun',
    example: 'いくらですか',
    exampleRuby: [],
    exampleKorean: '얼마입니까'
  },
  {
    kanji: '池',
    hiragana: 'いけ',
    romaji: 'ike',
    korean: '연못',
    english: 'pond',
    partOfSpeech: 'noun',
    example: '池の魚',
    exampleRuby: [{ 池: 'いけ' }, { 魚: 'さかな' }],
    exampleKorean: '연못의 물고기'
  },
  {
    kanji: '医者',
    hiragana: 'いしゃ',
    romaji: 'isha',
    korean: '의사',
    english: 'medical doctor',
    partOfSpeech: 'noun',
    example: '医者に診てもらう',
    exampleRuby: [{ 医者: 'いしゃ' }, { 診: 'み' }],
    exampleKorean: '의사에게 진찰받다'
  },
  {
    kanji: '椅子',
    hiragana: 'いす',
    romaji: 'isu',
    korean: '의자',
    english: 'chair',
    partOfSpeech: 'noun',
    example: '椅子に座る',
    exampleRuby: [{ 椅子: 'いす' }, { 座: 'すわ' }],
    exampleKorean: '의자에 앉다'
  },
  {
    kanji: '忙しい',
    hiragana: 'いそがしい',
    romaji: 'isogashii',
    korean: '바쁜',
    english: 'busy',
    partOfSpeech: 'adjective',
    example: '忙しい日',
    exampleRuby: [{ 忙: 'いそが' }, { 日: 'ひ' }],
    exampleKorean: '바쁜 날'
  },
  {
    kanji: '痛い',
    hiragana: 'いたい',
    romaji: 'itai',
    korean: '아픈',
    english: 'painful',
    partOfSpeech: 'adjective',
    example: '頭が痛い',
    exampleRuby: [{ 頭: 'あたま' }, { 痛: 'いた' }],
    exampleKorean: '머리가 아프다'
  },
  {
    kanji: '一日',
    hiragana: 'いちにち',
    romaji: 'ichinichi',
    korean: '하루',
    english: 'first of the month, one day',
    partOfSpeech: 'noun',
    example: '一日目',
    exampleRuby: [{ 一日: 'いちにち' }, { 目: 'め' }],
    exampleKorean: '첫날'
  },
  {
    kanji: '',
    hiragana: 'いちばん',
    romaji: 'ichiban',
    korean: '가장',
    english: 'best, first',
    partOfSpeech: 'adverb',
    example: 'いちばん好き',
    exampleRuby: [{ 好: 'す' }],
    exampleKorean: '가장 좋아하는'
  },
  {
    kanji: '',
    hiragana: 'いつ',
    romaji: 'itsu',
    korean: '언제',
    english: 'when',
    partOfSpeech: 'pronoun',
    example: 'いつ来ますか',
    exampleRuby: [{ 来: 'き' }],
    exampleKorean: '언제 옵니까'
  },
  {
    kanji: '五日',
    hiragana: 'いつか',
    romaji: 'itsuka',
    korean: '5일',
    english: 'five days, fifth day',
    partOfSpeech: 'noun',
    example: '五日目',
    exampleRuby: [{ 五日: 'いつか' }, { 目: 'め' }],
    exampleKorean: '5일째'
  },
  {
    kanji: '一緒',
    hiragana: 'いっしょ',
    romaji: 'issho',
    korean: '함께',
    english: 'together',
    partOfSpeech: 'adverb',
    example: '一緒に行く',
    exampleRuby: [{ 一緒: 'いっしょ' }, { 行: 'い' }],
    exampleKorean: '함께 가다'
  },
  {
    kanji: '五つ',
    hiragana: 'いつつ',
    romaji: 'itsutsu',
    korean: '다섯',
    english: 'five',
    partOfSpeech: 'number',
    example: '五つのりんご',
    exampleRuby: [{ 五: 'いつ' }],
    exampleKorean: '다섯 개의 사과'
  },
  {
    kanji: '',
    hiragana: 'いつも',
    romaji: 'itsumo',
    korean: '항상',
    english: 'always',
    partOfSpeech: 'adverb',
    example: 'いつもありがとう',
    exampleRuby: [],
    exampleKorean: '항상 고맙습니다'
  },
  {
    kanji: '犬',
    hiragana: 'いぬ',
    romaji: 'inu',
    korean: '개',
    english: 'dog',
    partOfSpeech: 'noun',
    example: '犬を飼う',
    exampleRuby: [{ 犬: 'いぬ' }, { 飼: 'か' }],
    exampleKorean: '개를 기르다'
  },
  {
    kanji: '今',
    hiragana: 'いま',
    romaji: 'ima',
    korean: '지금',
    english: 'now',
    partOfSpeech: 'adverb',
    example: '今何時ですか',
    exampleRuby: [{ 今: 'いま' }, { 何: 'なん' }, { 時: 'じ' }],
    exampleKorean: '지금 몇 시입니까'
  },
  {
    kanji: '意味',
    hiragana: 'いみ',
    romaji: 'imi',
    korean: '의미',
    english: 'meaning',
    partOfSpeech: 'noun',
    example: '言葉の意味',
    exampleRuby: [{ 言葉: 'ことば' }, { 意味: 'いみ' }],
    exampleKorean: '단어의 의미'
  },
  {
    kanji: '妹',
    hiragana: 'いもうと',
    romaji: 'imouto',
    korean: '여동생',
    english: 'younger sister',
    partOfSpeech: 'noun',
    example: '妹がいる',
    exampleRuby: [{ 妹: 'いもうと' }],
    exampleKorean: '여동생이 있다'
  },
  {
    kanji: '',
    hiragana: 'いや',
    romaji: 'iya',
    korean: '싫은',
    english: 'unpleasant, no',
    partOfSpeech: 'adjective',
    example: 'いやな天気',
    exampleRuby: [{ 天気: 'てんき' }],
    exampleKorean: '싫은 날씨'
  },
  {
    kanji: '入口',
    hiragana: 'いりぐち',
    romaji: 'iriguchi',
    korean: '입구',
    english: 'entrance',
    partOfSpeech: 'noun',
    example: '入口はこちら',
    exampleRuby: [{ 入口: 'いりぐち' }],
    exampleKorean: '입구는 이쪽입니다'
  },
  {
    kanji: '居る',
    hiragana: 'いる',
    romaji: 'iru',
    korean: '있다',
    english: 'to be, to have (animate objects)',
    partOfSpeech: 'verb',
    example: '猫が居る',
    exampleRuby: [{ 猫: 'ねこ' }, { 居: 'い' }],
    exampleKorean: '고양이가 있다'
  },
  {
    kanji: '要る',
    hiragana: 'いる',
    romaji: 'iru',
    korean: '필요하다',
    english: 'to need',
    partOfSpeech: 'verb',
    example: 'お金が要る',
    exampleRuby: [{ 金: 'かね' }, { 要: 'い' }],
    exampleKorean: '돈이 필요하다'
  },
  {
    kanji: '入れる',
    hiragana: 'いれる',
    romaji: 'ireru',
    korean: '넣다',
    english: 'to put in',
    partOfSpeech: 'verb',
    example: '箱に入れる',
    exampleRuby: [{ 箱: 'はこ' }, { 入: 'い' }],
    exampleKorean: '상자에 넣다'
  },
  {
    kanji: '色',
    hiragana: 'いろ',
    romaji: 'iro',
    korean: '색',
    english: 'colour',
    partOfSpeech: 'noun',
    example: '色を選ぶ',
    exampleRuby: [{ 色: 'いろ' }, { 選: 'えら' }],
    exampleKorean: '색을 선택하다'
  },
  {
    kanji: '',
    hiragana: 'いろいろ',
    romaji: 'iroiro',
    korean: '여러가지',
    english: 'various',
    partOfSpeech: 'adjective',
    example: 'いろいろな本',
    exampleRuby: [{ 本: 'ほん' }],
    exampleKorean: '여러가지 책'
  },
  {
    kanji: '上',
    hiragana: 'うえ',
    romaji: 'ue',
    korean: '위',
    english: 'on top of, above',
    partOfSpeech: 'noun',
    example: '机の上',
    exampleRuby: [{ 机: 'つくえ' }, { 上: 'うえ' }],
    exampleKorean: '책상 위'
  },
  {
    kanji: '後ろ',
    hiragana: 'うしろ',
    romaji: 'ushiro',
    korean: '뒤',
    english: 'behind',
    partOfSpeech: 'noun',
    example: '後ろを見る',
    exampleRuby: [{ 後: 'うし' }, { 見: 'み' }],
    exampleKorean: '뒤를 보다'
  },
  {
    kanji: '薄い',
    hiragana: 'うすい',
    romaji: 'usui',
    korean: '얇은',
    english: 'thin, weak',
    partOfSpeech: 'adjective',
    example: '薄い紙',
    exampleRuby: [{ 薄: 'うす' }, { 紙: 'かみ' }],
    exampleKorean: '얇은 종이'
  },
  {
    kanji: '歌',
    hiragana: 'うた',
    romaji: 'uta',
    korean: '노래',
    english: 'song',
    partOfSpeech: 'noun',
    example: '歌を歌う',
    exampleRuby: [{ 歌: 'うた' }],
    exampleKorean: '노래를 부르다'
  },
  {
    kanji: '歌う',
    hiragana: 'うたう',
    romaji: 'utau',
    korean: '노래하다',
    english: 'to sing',
    partOfSpeech: 'verb',
    example: '歌を歌う',
    exampleRuby: [{ 歌: 'うた' }],
    exampleKorean: '노래를 부르다'
  },
  {
    kanji: '生まれる',
    hiragana: 'うまれる',
    romaji: 'umareru',
    korean: '태어나다',
    english: 'to be born',
    partOfSpeech: 'verb',
    example: '赤ちゃんが生まれる',
    exampleRuby: [{ 生: 'う' }],
    exampleKorean: '아기가 태어나다'
  },
  {
    kanji: '海',
    hiragana: 'うみ',
    romaji: 'umi',
    korean: '바다',
    english: 'sea',
    partOfSpeech: 'noun',
    example: '海に行く',
    exampleRuby: [{ 海: 'うみ' }, { 行: 'い' }],
    exampleKorean: '바다에 가다'
  },
  {
    kanji: '売る',
    hiragana: 'うる',
    romaji: 'uru',
    korean: '팔다',
    english: 'to sell',
    partOfSpeech: 'verb',
    example: '本を売る',
    exampleRuby: [{ 本: 'ほん' }, { 売: 'う' }],
    exampleKorean: '책을 팔다'
  },
  {
    kanji: '',
    hiragana: 'うるさい',
    romaji: 'urusai',
    korean: '시끄러운',
    english: 'noisy, annoying',
    partOfSpeech: 'adjective',
    example: 'うるさい音',
    exampleRuby: [{ 音: 'おと' }],
    exampleKorean: '시끄러운 소리'
  },
  {
    kanji: '上着',
    hiragana: 'うわぎ',
    romaji: 'uwagi',
    korean: '겉옷',
    english: 'jacket',
    partOfSpeech: 'noun',
    example: '上着を着る',
    exampleRuby: [{ 上着: 'うわぎ' }, { 着: 'き' }],
    exampleKorean: '겉옷을 입다'
  },
  {
    kanji: '絵',
    hiragana: 'え',
    romaji: 'e',
    korean: '그림',
    english: 'picture',
    partOfSpeech: 'noun',
    example: '絵を描く',
    exampleRuby: [{ 絵: 'え' }, { 描: 'か' }],
    exampleKorean: '그림을 그리다'
  },
  {
    kanji: '映画',
    hiragana: 'えいが',
    romaji: 'eiga',
    korean: '영화',
    english: 'movie',
    partOfSpeech: 'noun',
    example: '映画を見る',
    exampleRuby: [{ 映画: 'えいが' }, { 見: 'み' }],
    exampleKorean: '영화를 보다'
  },
  {
    kanji: '映画館',
    hiragana: 'えいがかん',
    romaji: 'eigakan',
    korean: '영화관',
    english: 'cinema',
    partOfSpeech: 'noun',
    example: '映画館に行く',
    exampleRuby: [{ 映画館: 'えいがかん' }, { 行: 'い' }],
    exampleKorean: '영화관에 가다'
  },
  {
    kanji: '英語',
    hiragana: 'えいご',
    romaji: 'eigo',
    korean: '영어',
    english: 'English language',
    partOfSpeech: 'noun',
    example: '英語を勉強する',
    exampleRuby: [{ 英語: 'えいご' }, { 勉強: 'べんきょう' }],
    exampleKorean: '영어를 공부하다'
  },
  {
    kanji: '',
    hiragana: 'ええ',
    romaji: 'ee',
    korean: '예',
    english: 'yes',
    partOfSpeech: 'interjection',
    example: 'ええ、そうです',
    exampleRuby: [],
    exampleKorean: '예, 그렇습니다'
  },
  {
    kanji: '駅',
    hiragana: 'えき',
    romaji: 'eki',
    korean: '역',
    english: 'station',
    partOfSpeech: 'noun',
    example: '薬を飲む',
    exampleRuby: [{ 薬: 'くすり' }, { 飲: 'の' }],
    exampleKorean: '약을 먹다'
  }
]

// 배열을 랜덤하게 섞는 함수
export const shuffleArray = (array) => {
  const shuffled = [...array]
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }
  return shuffled
}

