// 단어장 데이터
export const vocabulary = [
  {
    kanji: '会う',
    hiragana: 'あう',
    romaji: 'au',
    korean: '만나다',
    english: 'meet',
    partOfSpeech: 'verb',
    example: '友達に会う',
    exampleHiragana: 'ともだちにあう',
    exampleRomaji: 'tomodachi ni au',
    exampleKorean: '친구를 만나다'
  },
  {
    kanji: '青い',
    hiragana: 'あおい',
    romaji: 'aoi',
    korean: '푸른',
    english: 'blue',
    partOfSpeech: 'adjective',
    example: '青い空',
    exampleHiragana: 'あおいそら',
    exampleRomaji: 'aoi sora',
    exampleKorean: '푸른 하늘'
  },
  {
    kanji: '赤い',
    hiragana: 'あかい',
    romaji: 'akai',
    korean: '빨간',
    english: 'red',
    partOfSpeech: 'adjective',
    example: '赤い花',
    exampleHiragana: 'あかいはな',
    exampleRomaji: 'akai hana',
    exampleKorean: '빨간 꽃'
  },
  {
    kanji: '明るい',
    hiragana: 'あかるい',
    romaji: 'akarui',
    korean: '밝은',
    english: 'bright',
    partOfSpeech: 'adjective',
    example: '明るい部屋',
    exampleHiragana: 'あかるいへや',
    exampleRomaji: 'akarui heya',
    exampleKorean: '밝은 방'
  },
  {
    kanji: '秋',
    hiragana: 'あき',
    romaji: 'aki',
    korean: '가을',
    english: 'autumn',
    partOfSpeech: 'noun',
    example: '秋が好きです',
    exampleHiragana: 'あきがすきです',
    exampleRomaji: 'aki ga suki desu',
    exampleKorean: '가을을 좋아합니다'
  },
  {
    kanji: '開く',
    hiragana: 'あく',
    romaji: 'aku',
    korean: '열리다',
    english: 'to open, to become open',
    partOfSpeech: 'verb',
    example: 'ドアが開く',
    exampleHiragana: 'どあがあく',
    exampleRomaji: 'doa ga aku',
    exampleKorean: '문이 열리다'
  },
  {
    kanji: '開ける',
    hiragana: 'あける',
    romaji: 'akeru',
    korean: '열기',
    english: 'to open',
    partOfSpeech: 'verb',
    example: '窓を開ける',
    exampleHiragana: 'まどをあける',
    exampleRomaji: 'mado o akeru',
    exampleKorean: '창문을 열다'
  },
  {
    kanji: '',
    hiragana: 'あげる',
    romaji: 'ageru',
    korean: '주다',
    english: 'to give',
    partOfSpeech: 'verb',
    example: 'プレゼントをあげる',
    exampleHiragana: 'ぷれぜんとをあげる',
    exampleRomaji: 'purezento o ageru',
    exampleKorean: '선물을 주다'
  },
  {
    kanji: '朝',
    hiragana: 'あさ',
    romaji: 'asa',
    korean: '아침',
    english: 'morning',
    partOfSpeech: 'noun',
    example: '朝の散歩',
    exampleHiragana: 'あさのさんぽ',
    exampleRomaji: 'asa no sanpo',
    exampleKorean: '아침 산책'
  },
  {
    kanji: '朝ご飯',
    hiragana: 'あさごはん',
    romaji: 'asa gohan',
    korean: '아침밥',
    english: 'breakfast',
    partOfSpeech: 'noun',
    example: '朝ご飯を食べる',
    exampleHiragana: 'あさごはんをたべる',
    exampleRomaji: 'asa gohan o taberu',
    exampleKorean: '아침밥을 먹다'
  },
  {
    kanji: '明後日',
    hiragana: 'あさって',
    romaji: 'asatte',
    korean: '모레',
    english: 'day after tomorrow',
    partOfSpeech: 'noun',
    example: '明後日会いましょう',
    exampleHiragana: 'あさってあいましょう',
    exampleRomaji: 'asatte ai mashou',
    exampleKorean: '모레 만나요'
  },
  {
    kanji: '足',
    hiragana: 'あし',
    romaji: 'ashi',
    korean: '다리',
    english: 'foot, leg',
    partOfSpeech: 'noun',
    example: '足が痛い',
    exampleHiragana: 'あしがいたい',
    exampleRomaji: 'ashi ga itai',
    exampleKorean: '다리가 아프다'
  },
  {
    kanji: '明日',
    hiragana: 'あした',
    romaji: 'ashita',
    korean: '내일',
    english: 'tomorrow',
    partOfSpeech: 'noun',
    example: '明日は雨です',
    exampleHiragana: 'あしたはあめです',
    exampleRomaji: 'ashita wa ame desu',
    exampleKorean: '내일은 비입니다'
  },
  {
    kanji: '',
    hiragana: 'あそこ',
    romaji: 'asoko',
    korean: '저기',
    english: 'over there',
    partOfSpeech: 'noun',
    example: 'あそこに本があります',
    exampleHiragana: 'あそこにほんがあります',
    exampleRomaji: 'asoko ni hon ga arimasu',
    exampleKorean: '저기에 책이 있습니다'
  },
  {
    kanji: '遊ぶ',
    hiragana: 'あそぶ',
    romaji: 'asobu',
    korean: '놀다',
    english: 'to play',
    partOfSpeech: 'verb',
    example: '公園で遊ぶ',
    exampleHiragana: 'こうえんであそぶ',
    exampleRomaji: 'kouen de asobu',
    exampleKorean: '공원에서 놀다'
  },
  {
    kanji: '暖かい',
    hiragana: 'あたたかい',
    romaji: 'atatakai',
    korean: '따뜻한',
    english: 'warm',
    partOfSpeech: 'adjective',
    example: '暖かい日',
    exampleHiragana: 'あたたかいひ',
    exampleRomaji: 'atatakai hi',
    exampleKorean: '따뜻한 날'
  },
  {
    kanji: '頭',
    hiragana: 'あたま',
    romaji: 'atama',
    korean: '머리',
    english: 'head',
    partOfSpeech: 'noun',
    example: '頭が痛い',
    exampleHiragana: 'あたまがいたい',
    exampleRomaji: 'atama ga itai',
    exampleKorean: '머리가 아프다'
  },
  {
    kanji: '新しい',
    hiragana: 'あたらしい',
    romaji: 'atarashii',
    korean: '새로운',
    english: 'new',
    partOfSpeech: 'adjective',
    example: '新しい車',
    exampleHiragana: 'あたらしいくるま',
    exampleRomaji: 'atarashii kuruma',
    exampleKorean: '새로운 차'
  },
  {
    kanji: '',
    hiragana: 'あちら',
    romaji: 'achira',
    korean: '저쪽',
    english: 'there',
    partOfSpeech: 'noun',
    example: 'あちらを見てください',
    exampleHiragana: 'あちらをみてください',
    exampleRomaji: 'achira o mite kudasai',
    exampleKorean: '저쪽을 보세요'
  },
  {
    kanji: '暑い',
    hiragana: 'あつい',
    romaji: 'atsui',
    korean: '덥다',
    english: 'hot',
    partOfSpeech: 'adjective',
    example: '今日は暑いです',
    exampleHiragana: 'きょうはあついです',
    exampleRomaji: 'kyou wa atsui desu',
    exampleKorean: '오늘은 덥습니다'
  },
  {
    kanji: '熱い',
    hiragana: 'あつい',
    romaji: 'atsui',
    korean: '뜨겁다',
    english: 'hot to the touch',
    partOfSpeech: 'adjective',
    example: '熱いお茶',
    exampleHiragana: 'あついおちゃ',
    exampleRomaji: 'atsui ocha',
    exampleKorean: '뜨거운 차'
  },
  {
    kanji: '厚い',
    hiragana: 'あつい',
    romaji: 'atsui',
    korean: '두꺼운',
    english: 'thick, deep, kind',
    partOfSpeech: 'adjective',
    example: '厚い本',
    exampleHiragana: 'あついほん',
    exampleRomaji: 'atsui hon',
    exampleKorean: '두꺼운 책'
  },
  {
    kanji: '',
    hiragana: 'あっち',
    romaji: 'acchi',
    korean: '저기',
    english: 'over there',
    partOfSpeech: 'noun',
    example: 'あっちを見て',
    exampleHiragana: 'あっちをみて',
    exampleRomaji: 'acchi o mite',
    exampleKorean: '저기를 봐'
  },
  {
    kanji: '後',
    hiragana: 'あと',
    romaji: 'ato',
    korean: '나중에',
    english: 'afterwards, later',
    partOfSpeech: 'adverb',
    example: '後で会いましょう',
    exampleHiragana: 'あとであいましょう',
    exampleRomaji: 'ato de ai mashou',
    exampleKorean: '나중에 만나요'
  },
  {
    kanji: '',
    hiragana: 'あなた',
    romaji: 'anata',
    korean: '당신',
    english: 'you',
    partOfSpeech: 'pronoun',
    example: 'あなたは誰ですか',
    exampleHiragana: 'あなたはだれですか',
    exampleRomaji: 'anata wa dare desu ka',
    exampleKorean: '당신은 누구입니까'
  },
  {
    kanji: '兄',
    hiragana: 'あに',
    romaji: 'ani',
    korean: '형/오빠',
    english: 'older brother',
    partOfSpeech: 'noun',
    example: '兄が来ました',
    exampleHiragana: 'あにがきました',
    exampleRomaji: 'ani ga kimashita',
    exampleKorean: '형이 왔습니다'
  },
  {
    kanji: '姉',
    hiragana: 'あね',
    romaji: 'ane',
    korean: '누나/언니',
    english: 'older sister',
    partOfSpeech: 'noun',
    example: '姉と話す',
    exampleHiragana: 'あねとはなす',
    exampleRomaji: 'ane to hanasu',
    exampleKorean: '언니와 이야기하다'
  },
  {
    kanji: '',
    hiragana: 'あの',
    romaji: 'ano',
    korean: '그',
    english: 'that over there',
    partOfSpeech: 'adjective',
    example: 'あの本',
    exampleHiragana: 'あのほん',
    exampleRomaji: 'ano hon',
    exampleKorean: '그 책'
  },
  {
    kanji: '',
    hiragana: 'アパート',
    romaji: 'apaato',
    korean: '아파트',
    english: 'apartment',
    partOfSpeech: 'noun',
    example: 'アパートに住む',
    exampleHiragana: 'あぱーとにすむ',
    exampleRomaji: 'apaato ni sumu',
    exampleKorean: '아파트에 살다'
  },
  {
    kanji: '浴びる',
    hiragana: 'あびる',
    romaji: 'abiru',
    korean: '목욕하다',
    english: 'to bathe, to shower',
    partOfSpeech: 'verb',
    example: 'シャワーを浴びる',
    exampleHiragana: 'しゃわーをあびる',
    exampleRomaji: 'shawaa o abiru',
    exampleKorean: '샤워를 하다'
  },
  {
    kanji: '危ない',
    hiragana: 'あぶない',
    romaji: 'abunai',
    korean: '위험한',
    english: 'dangerous',
    partOfSpeech: 'adjective',
    example: '危ない道',
    exampleHiragana: 'あぶないみち',
    exampleRomaji: 'abunai michi',
    exampleKorean: '위험한 길'
  },
  {
    kanji: '甘い',
    hiragana: 'あまい',
    romaji: 'amai',
    korean: '달콤한',
    english: 'sweet',
    partOfSpeech: 'adjective',
    example: '甘いケーキ',
    exampleHiragana: 'あまいけーき',
    exampleRomaji: 'amai keeki',
    exampleKorean: '달콤한 케이크'
  },
  {
    kanji: '',
    hiragana: 'あまり',
    romaji: 'amari',
    korean: '별로',
    english: 'not very',
    partOfSpeech: 'adverb',
    example: 'あまり好きじゃない',
    exampleHiragana: 'あまりすきじゃない',
    exampleRomaji: 'amari suki ja nai',
    exampleKorean: '별로 좋아하지 않다'
  },
  {
    kanji: '雨',
    hiragana: 'あめ',
    romaji: 'ame',
    korean: '비',
    english: 'rain',
    partOfSpeech: 'noun',
    example: '雨が降る',
    exampleHiragana: 'あめがふる',
    exampleRomaji: 'ame ga furu',
    exampleKorean: '비가 오다'
  },
  {
    kanji: '飴',
    hiragana: 'あめ',
    romaji: 'ame',
    korean: '사탕',
    english: 'candy',
    partOfSpeech: 'noun',
    example: '飴を食べる',
    exampleHiragana: 'あめをたべる',
    exampleRomaji: 'ame o taberu',
    exampleKorean: '사탕을 먹다'
  },
  {
    kanji: '洗う',
    hiragana: 'あらう',
    romaji: 'arau',
    korean: '씻다',
    english: 'to wash',
    partOfSpeech: 'verb',
    example: '手を洗う',
    exampleHiragana: 'てをあらう',
    exampleRomaji: 'te o arau',
    exampleKorean: '손을 씻다'
  },
  {
    kanji: '',
    hiragana: 'ある',
    romaji: 'aru',
    korean: '있다',
    english: 'to be, to have (inanimate objects)',
    partOfSpeech: 'verb',
    example: '本がある',
    exampleHiragana: 'ほんがある',
    exampleRomaji: 'hon ga aru',
    exampleKorean: '책이 있다'
  },
  {
    kanji: '歩く',
    hiragana: 'あるく',
    romaji: 'aruku',
    korean: '걷다',
    english: 'to walk',
    partOfSpeech: 'verb',
    example: '公園を歩く',
    exampleHiragana: 'こうえんをあるく',
    exampleRomaji: 'kouen o aruku',
    exampleKorean: '공원을 걷다'
  },
  {
    kanji: '',
    hiragana: 'あれ',
    romaji: 'are',
    korean: '그것',
    english: 'that',
    partOfSpeech: 'pronoun',
    example: 'あれは何ですか',
    exampleHiragana: 'あれはなんですか',
    exampleRomaji: 'are wa nan desu ka',
    exampleKorean: '그것은 무엇입니까'
  },
  {
    kanji: '',
    hiragana: 'いい',
    romaji: 'ii',
    korean: '좋은',
    english: 'good',
    partOfSpeech: 'adjective',
    example: 'いい天気',
    exampleHiragana: 'いいてんき',
    exampleRomaji: 'ii tenki',
    exampleKorean: '좋은 날씨'
  },
  {
    kanji: '',
    hiragana: 'いいえ',
    romaji: 'iie',
    korean: '아니오',
    english: 'no',
    partOfSpeech: 'interjection',
    example: 'いいえ、違います',
    exampleHiragana: 'いいえ、ちがいます',
    exampleRomaji: 'iie, chigaimasu',
    exampleKorean: '아니오, 틀렸습니다'
  },
  {
    kanji: '言う',
    hiragana: 'いう',
    romaji: 'iu',
    korean: '말하다',
    english: 'to say',
    partOfSpeech: 'verb',
    example: 'ありがとうと言う',
    exampleHiragana: 'ありがとうという',
    exampleRomaji: 'arigatou to iu',
    exampleKorean: '고맙다고 말하다'
  },
  {
    kanji: '家',
    hiragana: 'いえ',
    romaji: 'ie',
    korean: '집',
    english: 'house',
    partOfSpeech: 'noun',
    example: '家に帰る',
    exampleHiragana: 'いえにかえる',
    exampleRomaji: 'ie ni kaeru',
    exampleKorean: '집에 돌아가다'
  },
  {
    kanji: '',
    hiragana: 'いかが',
    romaji: 'ikaga',
    korean: '어떻게',
    english: 'how',
    partOfSpeech: 'adverb',
    example: 'いかがですか',
    exampleHiragana: 'いかがですか',
    exampleRomaji: 'ikaga desu ka',
    exampleKorean: '어떠십니까'
  },
  {
    kanji: '行く',
    hiragana: 'いく',
    romaji: 'iku',
    korean: '가다',
    english: 'to go',
    partOfSpeech: 'verb',
    example: '学校に行く',
    exampleHiragana: 'がっこうにいく',
    exampleRomaji: 'gakkou ni iku',
    exampleKorean: '학교에 가다'
  },
  {
    kanji: '',
    hiragana: 'いくつ',
    romaji: 'ikutsu',
    korean: '몇',
    english: 'how many, how old',
    partOfSpeech: 'pronoun',
    example: 'いくつありますか',
    exampleHiragana: 'いくつありますか',
    exampleRomaji: 'ikutsu arimasu ka',
    exampleKorean: '몇 개 있습니까'
  },
  {
    kanji: '',
    hiragana: 'いくら',
    romaji: 'ikura',
    korean: '얼마',
    english: 'how much',
    partOfSpeech: 'pronoun',
    example: 'いくらですか',
    exampleHiragana: 'いくらですか',
    exampleRomaji: 'ikura desu ka',
    exampleKorean: '얼마입니까'
  },
  {
    kanji: '池',
    hiragana: 'いけ',
    romaji: 'ike',
    korean: '연못',
    english: 'pond',
    partOfSpeech: 'noun',
    example: '池の魚',
    exampleHiragana: 'いけのさかな',
    exampleRomaji: 'ike no sakana',
    exampleKorean: '연못의 물고기'
  },
  {
    kanji: '医者',
    hiragana: 'いしゃ',
    romaji: 'isha',
    korean: '의사',
    english: 'medical doctor',
    partOfSpeech: 'noun',
    example: '医者に診てもらう',
    exampleHiragana: 'いしゃにみてもらう',
    exampleRomaji: 'isha ni mite morau',
    exampleKorean: '의사에게 진찰받다'
  },
  {
    kanji: '椅子',
    hiragana: 'いす',
    romaji: 'isu',
    korean: '의자',
    english: 'chair',
    partOfSpeech: 'noun',
    example: '椅子に座る',
    exampleHiragana: 'いすにすわる',
    exampleRomaji: 'isu ni suwaru',
    exampleKorean: '의자에 앉다'
  },
  {
    kanji: '忙しい',
    hiragana: 'いそがしい',
    romaji: 'isogashii',
    korean: '바쁜',
    english: 'busy',
    partOfSpeech: 'adjective',
    example: '忙しい日',
    exampleHiragana: 'いそがしいひ',
    exampleRomaji: 'isogashii hi',
    exampleKorean: '바쁜 날'
  },
  {
    kanji: '痛い',
    hiragana: 'いたい',
    romaji: 'itai',
    korean: '아픈',
    english: 'painful',
    partOfSpeech: 'adjective',
    example: '頭が痛い',
    exampleHiragana: 'あたまがいたい',
    exampleRomaji: 'atama ga itai',
    exampleKorean: '머리가 아프다'
  },
  {
    kanji: '一日',
    hiragana: 'いちにち',
    romaji: 'ichinichi',
    korean: '하루',
    english: 'first of the month, one day',
    partOfSpeech: 'noun',
    example: '一日目',
    exampleHiragana: 'いちにちめ',
    exampleRomaji: 'ichinichi me',
    exampleKorean: '첫날'
  },
  {
    kanji: '',
    hiragana: 'いちばん',
    romaji: 'ichiban',
    korean: '가장',
    english: 'best, first',
    partOfSpeech: 'adverb',
    example: 'いちばん好き',
    exampleHiragana: 'いちばんすき',
    exampleRomaji: 'ichiban suki',
    exampleKorean: '가장 좋아하는'
  },
  {
    kanji: '',
    hiragana: 'いつ',
    romaji: 'itsu',
    korean: '언제',
    english: 'when',
    partOfSpeech: 'pronoun',
    example: 'いつ来ますか',
    exampleHiragana: 'いつきますか',
    exampleRomaji: 'itsu kimasu ka',
    exampleKorean: '언제 옵니까'
  },
  {
    kanji: '五日',
    hiragana: 'いつか',
    romaji: 'itsuka',
    korean: '5일',
    english: 'five days, fifth day',
    partOfSpeech: 'noun',
    example: '五日目',
    exampleHiragana: 'いつかめ',
    exampleRomaji: 'itsuka me',
    exampleKorean: '5일째'
  },
  {
    kanji: '一緒',
    hiragana: 'いっしょ',
    romaji: 'issho',
    korean: '함께',
    english: 'together',
    partOfSpeech: 'adverb',
    example: '一緒に行く',
    exampleHiragana: 'いっしょにいく',
    exampleRomaji: 'issho ni iku',
    exampleKorean: '함께 가다'
  },
  {
    kanji: '五つ',
    hiragana: 'いつつ',
    romaji: 'itsutsu',
    korean: '다섯',
    english: 'five',
    partOfSpeech: 'number',
    example: '五つのりんご',
    exampleHiragana: 'いつつのりんご',
    exampleRomaji: 'itsutsu no ringo',
    exampleKorean: '다섯 개의 사과'
  },
  {
    kanji: '',
    hiragana: 'いつも',
    romaji: 'itsumo',
    korean: '항상',
    english: 'always',
    partOfSpeech: 'adverb',
    example: 'いつもありがとう',
    exampleHiragana: 'いつもありがとう',
    exampleRomaji: 'itsumo arigatou',
    exampleKorean: '항상 고맙습니다'
  },
  {
    kanji: '犬',
    hiragana: 'いぬ',
    romaji: 'inu',
    korean: '개',
    english: 'dog',
    partOfSpeech: 'noun',
    example: '犬を飼う',
    exampleHiragana: 'いぬをかう',
    exampleRomaji: 'inu o kau',
    exampleKorean: '개를 기르다'
  },
  {
    kanji: '今',
    hiragana: 'いま',
    romaji: 'ima',
    korean: '지금',
    english: 'now',
    partOfSpeech: 'adverb',
    example: '今何時ですか',
    exampleHiragana: 'いまなんじですか',
    exampleRomaji: 'ima nanji desu ka',
    exampleKorean: '지금 몇 시입니까'
  },
  {
    kanji: '意味',
    hiragana: 'いみ',
    romaji: 'imi',
    korean: '의미',
    english: 'meaning',
    partOfSpeech: 'noun',
    example: '言葉の意味',
    exampleHiragana: 'ことばのいみ',
    exampleRomaji: 'kotoba no imi',
    exampleKorean: '단어의 의미'
  },
  {
    kanji: '妹',
    hiragana: 'いもうと',
    romaji: 'imouto',
    korean: '여동생',
    english: 'younger sister',
    partOfSpeech: 'noun',
    example: '妹がいる',
    exampleHiragana: 'いもうとがいる',
    exampleRomaji: 'imouto ga iru',
    exampleKorean: '여동생이 있다'
  },
  {
    kanji: '',
    hiragana: 'いや',
    romaji: 'iya',
    korean: '싫은',
    english: 'unpleasant, no',
    partOfSpeech: 'adjective',
    example: 'いやな天気',
    exampleHiragana: 'いやなてんき',
    exampleRomaji: 'iya na tenki',
    exampleKorean: '싫은 날씨'
  },
  {
    kanji: '入口',
    hiragana: 'いりぐち',
    romaji: 'iriguchi',
    korean: '입구',
    english: 'entrance',
    partOfSpeech: 'noun',
    example: '入口はこちら',
    exampleHiragana: 'いりぐちはこちら',
    exampleRomaji: 'iriguchi wa kochira',
    exampleKorean: '입구는 이쪽입니다'
  },
  {
    kanji: '居る',
    hiragana: 'いる',
    romaji: 'iru',
    korean: '있다',
    english: 'to be, to have (animate objects)',
    partOfSpeech: 'verb',
    example: '猫が居る',
    exampleHiragana: 'ねこがいる',
    exampleRomaji: 'neko ga iru',
    exampleKorean: '고양이가 있다'
  },
  {
    kanji: '要る',
    hiragana: 'いる',
    romaji: 'iru',
    korean: '필요하다',
    english: 'to need',
    partOfSpeech: 'verb',
    example: 'お金が要る',
    exampleHiragana: 'おかねがいる',
    exampleRomaji: 'okane ga iru',
    exampleKorean: '돈이 필요하다'
  },
  {
    kanji: '入れる',
    hiragana: 'いれる',
    romaji: 'ireru',
    korean: '넣다',
    english: 'to put in',
    partOfSpeech: 'verb',
    example: '箱に入れる',
    exampleHiragana: 'はこにいれる',
    exampleRomaji: 'hako ni ireru',
    exampleKorean: '상자에 넣다'
  },
  {
    kanji: '色',
    hiragana: 'いろ',
    romaji: 'iro',
    korean: '색',
    english: 'colour',
    partOfSpeech: 'noun',
    example: '色を選ぶ',
    exampleHiragana: 'いろをえらぶ',
    exampleRomaji: 'iro o erabu',
    exampleKorean: '색을 선택하다'
  },
  {
    kanji: '',
    hiragana: 'いろいろ',
    romaji: 'iroiro',
    korean: '여러가지',
    english: 'various',
    partOfSpeech: 'adjective',
    example: 'いろいろな本',
    exampleHiragana: 'いろいろなほん',
    exampleRomaji: 'iroiro na hon',
    exampleKorean: '여러가지 책'
  },
  {
    kanji: '上',
    hiragana: 'うえ',
    romaji: 'ue',
    korean: '위',
    english: 'on top of, above',
    partOfSpeech: 'noun',
    example: '机の上',
    exampleHiragana: 'つくえのうえ',
    exampleRomaji: 'tsukue no ue',
    exampleKorean: '책상 위'
  },
  {
    kanji: '後ろ',
    hiragana: 'うしろ',
    romaji: 'ushiro',
    korean: '뒤',
    english: 'behind',
    partOfSpeech: 'noun',
    example: '後ろを見る',
    exampleHiragana: 'うしろをみる',
    exampleRomaji: 'ushiro o miru',
    exampleKorean: '뒤를 보다'
  },
  {
    kanji: '薄い',
    hiragana: 'うすい',
    romaji: 'usui',
    korean: '얇은',
    english: 'thin, weak',
    partOfSpeech: 'adjective',
    example: '薄い紙',
    exampleHiragana: 'うすいかみ',
    exampleRomaji: 'usui kami',
    exampleKorean: '얇은 종이'
  },
  {
    kanji: '歌',
    hiragana: 'うた',
    romaji: 'uta',
    korean: '노래',
    english: 'song',
    partOfSpeech: 'noun',
    example: '歌を歌う',
    exampleHiragana: 'うたをうたう',
    exampleRomaji: 'uta o utau',
    exampleKorean: '노래를 부르다'
  },
  {
    kanji: '歌う',
    hiragana: 'うたう',
    romaji: 'utau',
    korean: '노래하다',
    english: 'to sing',
    partOfSpeech: 'verb',
    example: '歌を歌う',
    exampleHiragana: 'うたをうたう',
    exampleRomaji: 'uta o utau',
    exampleKorean: '노래를 부르다'
  },
  {
    kanji: '生まれる',
    hiragana: 'うまれる',
    romaji: 'umareru',
    korean: '태어나다',
    english: 'to be born',
    partOfSpeech: 'verb',
    example: '赤ちゃんが生まれる',
    exampleHiragana: 'あかちゃんがうまれる',
    exampleRomaji: 'akachan ga umareru',
    exampleKorean: '아기가 태어나다'
  },
  {
    kanji: '海',
    hiragana: 'うみ',
    romaji: 'umi',
    korean: '바다',
    english: 'sea',
    partOfSpeech: 'noun',
    example: '海に行く',
    exampleHiragana: 'うみにいく',
    exampleRomaji: 'umi ni iku',
    exampleKorean: '바다에 가다'
  },
  {
    kanji: '売る',
    hiragana: 'うる',
    romaji: 'uru',
    korean: '팔다',
    english: 'to sell',
    partOfSpeech: 'verb',
    example: '本を売る',
    exampleHiragana: 'ほんをうる',
    exampleRomaji: 'hon o uru',
    exampleKorean: '책을 팔다'
  },
  {
    kanji: '',
    hiragana: 'うるさい',
    romaji: 'urusai',
    korean: '시끄러운',
    english: 'noisy, annoying',
    partOfSpeech: 'adjective',
    example: 'うるさい音',
    exampleHiragana: 'うるさいおと',
    exampleRomaji: 'urusai oto',
    exampleKorean: '시끄러운 소리'
  },
  {
    kanji: '上着',
    hiragana: 'うわぎ',
    romaji: 'uwagi',
    korean: '겉옷',
    english: 'jacket',
    partOfSpeech: 'noun',
    example: '上着を着る',
    exampleHiragana: 'うわぎをきる',
    exampleRomaji: 'uwagi o kiru',
    exampleKorean: '겉옷을 입다'
  },
  {
    kanji: '絵',
    hiragana: 'え',
    romaji: 'e',
    korean: '그림',
    english: 'picture',
    partOfSpeech: 'noun',
    example: '絵を描く',
    exampleHiragana: 'えをかく',
    exampleRomaji: 'e o kaku',
    exampleKorean: '그림을 그리다'
  },
  {
    kanji: '映画',
    hiragana: 'えいが',
    romaji: 'eiga',
    korean: '영화',
    english: 'movie',
    partOfSpeech: 'noun',
    example: '映画を見る',
    exampleHiragana: 'えいがをみる',
    exampleRomaji: 'eiga o miru',
    exampleKorean: '영화를 보다'
  },
  {
    kanji: '映画館',
    hiragana: 'えいがかん',
    romaji: 'eigakan',
    korean: '영화관',
    english: 'cinema',
    partOfSpeech: 'noun',
    example: '映画館に行く',
    exampleHiragana: 'えいがかんにいく',
    exampleRomaji: 'eigakan ni iku',
    exampleKorean: '영화관에 가다'
  },
  {
    kanji: '英語',
    hiragana: 'えいご',
    romaji: 'eigo',
    korean: '영어',
    english: 'English language',
    partOfSpeech: 'noun',
    example: '英語を勉強する',
    exampleHiragana: 'えいごをべんきょうする',
    exampleRomaji: 'eigo o benkyou suru',
    exampleKorean: '영어를 공부하다'
  },
  {
    kanji: '',
    hiragana: 'ええ',
    romaji: 'ee',
    korean: '예',
    english: 'yes',
    partOfSpeech: 'interjection',
    example: 'ええ、そうです',
    exampleHiragana: 'ええ、そうです',
    exampleRomaji: 'ee, sou desu',
    exampleKorean: '예, 그렇습니다'
  },
  {
    kanji: '駅',
    hiragana: 'えき',
    romaji: 'eki',
    korean: '역',
    english: 'station',
    partOfSpeech: 'noun',
    example: '駅に着く',
    exampleHiragana: 'えきにつく',
    exampleRomaji: 'eki ni tsuku',
    exampleKorean: '역에 도착하다'
  },
  {
    kanji: '',
    hiragana: 'エレベーター',
    romaji: 'erebeetaa',
    korean: '엘리베이터',
    english: 'elevator',
    partOfSpeech: 'noun',
    example: 'エレベーターに乗る',
    exampleHiragana: 'えれべーたーにのる',
    exampleRomaji: 'erebeetaa ni noru',
    exampleKorean: '엘리베이터를 타다'
  },
  {
    kanji: '鉛筆',
    hiragana: 'えんぴつ',
    romaji: 'enpitsu',
    korean: '연필',
    english: 'pencil',
    partOfSpeech: 'noun',
    example: '鉛筆で書く',
    exampleHiragana: 'えんぴつでかく',
    exampleRomaji: 'enpitsu de kaku',
    exampleKorean: '연필로 쓰다'
  },
  {
    kanji: '',
    hiragana: 'おいしい',
    romaji: 'oishii',
    korean: '맛있는',
    english: 'delicious',
    partOfSpeech: 'adjective',
    example: 'おいしい料理',
    exampleHiragana: 'おいしいりょうり',
    exampleRomaji: 'oishii ryouri',
    exampleKorean: '맛있는 요리'
  },
  {
    kanji: '多い',
    hiragana: 'おおい',
    romaji: 'ooi',
    korean: '많은',
    english: 'many',
    partOfSpeech: 'adjective',
    example: '人が多い',
    exampleHiragana: 'ひとがおおい',
    exampleRomaji: 'hito ga ooi',
    exampleKorean: '사람이 많다'
  },
  {
    kanji: '大きい',
    hiragana: 'おおきい',
    romaji: 'ookii',
    korean: '큰',
    english: 'big',
    partOfSpeech: 'adjective',
    example: '大きい家',
    exampleHiragana: 'おおきいいえ',
    exampleRomaji: 'ookii ie',
    exampleKorean: '큰 집'
  },
  {
    kanji: '大きな',
    hiragana: 'おおきな',
    romaji: 'ookina',
    korean: '큰',
    english: 'big',
    partOfSpeech: 'adjective',
    example: '大きな木',
    exampleHiragana: 'おおきなき',
    exampleRomaji: 'ookina ki',
    exampleKorean: '큰 나무'
  },
  {
    kanji: '大勢',
    hiragana: 'おおぜい',
    romaji: 'oozei',
    korean: '많은 사람',
    english: 'great number of people',
    partOfSpeech: 'noun',
    example: '大勢の人が来た',
    exampleHiragana: 'おおぜいのひとがきた',
    exampleRomaji: 'oozei no hito ga kita',
    exampleKorean: '많은 사람이 왔다'
  },
  {
    kanji: '',
    hiragana: 'おかあさん',
    romaji: 'okaasan',
    korean: '엄마',
    english: 'mother',
    partOfSpeech: 'noun',
    example: 'おかあさんがよぶ',
    exampleHiragana: 'おかあさんがよぶ',
    exampleRomaji: 'okaasan ga yobu',
    exampleKorean: '엄마가 부른다'
  },
  {
    kanji: '',
    hiragana: 'おかし',
    romaji: 'okashi',
    korean: '과자',
    english: 'sweets, candy',
    partOfSpeech: 'noun',
    example: 'おかしをたべる',
    exampleHiragana: 'おかしをたべる',
    exampleRomaji: 'okashi o taberu',
    exampleKorean: '과자를 먹다'
  },
  {
    kanji: '',
    hiragana: 'おかね',
    romaji: 'okane',
    korean: '돈',
    english: 'money',
    partOfSpeech: 'noun',
    example: 'おかねをはらう',
    exampleHiragana: 'おかねをはらう',
    exampleRomaji: 'okane o harau',
    exampleKorean: '돈을 지불하다'
  },
  {
    kanji: '起きる',
    hiragana: 'おきる',
    romaji: 'okiru',
    korean: '일어나다',
    english: 'to get up',
    partOfSpeech: 'verb',
    example: '朝早く起きる',
    exampleHiragana: 'あさはやくおきる',
    exampleRomaji: 'asa hayaku okiru',
    exampleKorean: '아침 일찍 일어나다'
  },
  {
    kanji: '置く',
    hiragana: 'おく',
    romaji: 'oku',
    korean: '두다',
    english: 'to put',
    partOfSpeech: 'verb',
    example: '机の上に置く',
    exampleHiragana: 'つくえのうえにおく',
    exampleRomaji: 'tsukue no ue ni oku',
    exampleKorean: '책상 위에 두다'
  },
  {
    kanji: '奥さん',
    hiragana: 'おくさん',
    romaji: 'okusan',
    korean: '부인',
    english: '(honorable) wife',
    partOfSpeech: 'noun',
    example: '奥さんは元気ですか',
    exampleHiragana: 'おくさんはげんきですか',
    exampleRomaji: 'okusan wa genki desu ka',
    exampleKorean: '부인은 건강하십니까'
  },
  {
    kanji: 'お酒',
    hiragana: 'おさけ',
    romaji: 'osake',
    korean: '술',
    english: 'alcohol, rice wine',
    partOfSpeech: 'noun',
    example: 'お酒を飲む',
    exampleHiragana: 'おさけをのむ',
    exampleRomaji: 'osake o nomu',
    exampleKorean: '술을 마시다'
  },
  {
    kanji: 'お皿',
    hiragana: 'おさら',
    romaji: 'osara',
    korean: '접시',
    english: 'plate, dish',
    partOfSpeech: 'noun',
    example: 'お皿を洗う',
    exampleHiragana: 'おさらをあらう',
    exampleRomaji: 'osara o arau',
    exampleKorean: '접시를 씻다'
  },
  {
    kanji: 'お祖父さん',
    hiragana: 'おじいさん',
    romaji: 'ojiisan',
    korean: '할아버지',
    english: 'grandfather, male senior',
    partOfSpeech: 'noun',
    example: 'お祖父さんが来ました',
    exampleHiragana: 'おじいさんがきました',
    exampleRomaji: 'ojiisan ga kimashita',
    exampleKorean: '할아버지가 오셨습니다'
  },
  {
    kanji: '教える',
    hiragana: 'おしえる',
    romaji: 'oshieru',
    korean: '가르치다',
    english: 'to teach, to tell',
    partOfSpeech: 'verb',
    example: '日本語を教える',
    exampleHiragana: 'にほんごをおしえる',
    exampleRomaji: 'nihongo o oshieru',
    exampleKorean: '일본어를 가르치다'
  },
  {
    kanji: '',
    hiragana: 'おじさん',
    romaji: 'ojisan',
    korean: '아저씨',
    english: 'uncle, middle aged gentleman',
    partOfSpeech: 'noun',
    example: 'おじさんに会う',
    exampleHiragana: 'おじさんにあう',
    exampleRomaji: 'ojisan ni au',
    exampleKorean: '아저씨를 만나다'
  },
  {
    kanji: '押す',
    hiragana: 'おす',
    romaji: 'osu',
    korean: '밀다',
    english: 'to push, to stamp something',
    partOfSpeech: 'verb',
    example: 'ボタンを押す',
    exampleHiragana: 'ぼたんをおす',
    exampleRomaji: 'botan o osu',
    exampleKorean: '버튼을 누르다'
  },
  {
    kanji: '遅い',
    hiragana: 'おそい',
    romaji: 'osoi',
    korean: '늦다',
    english: 'late, slow',
    partOfSpeech: 'adjective',
    example: '遅い時間',
    exampleHiragana: 'おそいじかん',
    exampleRomaji: 'osoi jikan',
    exampleKorean: '늦은 시간'
  },
  {
    kanji: 'お茶',
    hiragana: 'おちゃ',
    romaji: 'ocha',
    korean: '차',
    english: 'green tea',
    partOfSpeech: 'noun',
    example: 'お茶を飲む',
    exampleHiragana: 'おちゃをのむ',
    exampleRomaji: 'ocha o nomu',
    exampleKorean: '차를 마시다'
  },
  {
    kanji: 'お手洗い',
    hiragana: 'おてあらい',
    romaji: 'otearai',
    korean: '화장실',
    english: 'bathroom',
    partOfSpeech: 'noun',
    example: 'お手洗いはどこですか',
    exampleHiragana: 'おてあらいはどこですか',
    exampleRomaji: 'otearai wa doko desu ka',
    exampleKorean: '화장실은 어디입니까'
  },
  {
    kanji: 'お父さん',
    hiragana: 'おとうさん',
    romaji: 'otousan',
    korean: '아버지',
    english: '(honorable) father',
    partOfSpeech: 'noun',
    example: 'お父さんが帰る',
    exampleHiragana: 'おとうさんがかえる',
    exampleRomaji: 'otousan ga kaeru',
    exampleKorean: '아버지가 돌아오다'
  },
  {
    kanji: '弟',
    hiragana: 'おとうと',
    romaji: 'otouto',
    korean: '동생',
    english: 'younger brother',
    partOfSpeech: 'noun',
    example: '弟がいる',
    exampleHiragana: 'おとうとがいる',
    exampleRomaji: 'otouto ga iru',
    exampleKorean: '동생이 있다'
  },
  {
    kanji: '男',
    hiragana: 'おとこ',
    romaji: 'otoko',
    korean: '남자',
    english: 'Man',
    partOfSpeech: 'noun',
    example: '男の人が来た',
    exampleHiragana: 'おとこのひとがきた',
    exampleRomaji: 'otoko no hito ga kita',
    exampleKorean: '남자가 왔다'
  },
  {
    kanji: '男の子',
    hiragana: 'おとこのこ',
    romaji: 'otoko no ko',
    korean: '소년',
    english: 'Boy',
    partOfSpeech: 'noun',
    example: '男の子が遊ぶ',
    exampleHiragana: 'おとこのこがあそぶ',
    exampleRomaji: 'otoko no ko ga asobu',
    exampleKorean: '소년이 놀다'
  },
  {
    kanji: '一昨日',
    hiragana: 'おととい',
    romaji: 'ototoi',
    korean: '그저께',
    english: 'day before yesterday',
    partOfSpeech: 'noun',
    example: '一昨日会った',
    exampleHiragana: 'おとといあった',
    exampleRomaji: 'ototoi atta',
    exampleKorean: '그저께 만났다'
  },
  {
    kanji: '一昨年',
    hiragana: 'おととし',
    romaji: 'ototoshi',
    korean: '재작년',
    english: 'year before last',
    partOfSpeech: 'noun',
    example: '一昨年日本に行った',
    exampleHiragana: 'おととしにほんにいった',
    exampleRomaji: 'ototoshi nihon ni itta',
    exampleKorean: '재작년 일본에 갔다'
  },
  {
    kanji: '大人',
    hiragana: 'おとな',
    romaji: 'otona',
    korean: '성인',
    english: 'Adult',
    partOfSpeech: 'noun',
    example: '大人の切符',
    exampleHiragana: 'おとなのきっぷ',
    exampleRomaji: 'otona no kippu',
    exampleKorean: '성인 표'
  },
  {
    kanji: '',
    hiragana: 'おなか',
    romaji: 'onaka',
    korean: '배',
    english: 'stomach',
    partOfSpeech: 'noun',
    example: 'おなかが痛い',
    exampleHiragana: 'おなかがいたい',
    exampleRomaji: 'onaka ga itai',
    exampleKorean: '배가 아프다'
  },
  {
    kanji: '同じ',
    hiragana: 'おなじ',
    romaji: 'onaji',
    korean: '같은',
    english: 'same',
    partOfSpeech: 'adjective',
    example: '同じ色',
    exampleHiragana: 'おなじいろ',
    exampleRomaji: 'onaji iro',
    exampleKorean: '같은 색'
  },
  {
    kanji: 'お兄さん',
    hiragana: 'おにいさん',
    romaji: 'oniisan',
    korean: '형',
    english: '(honorable) older brother',
    partOfSpeech: 'noun',
    example: 'お兄さんが来る',
    exampleHiragana: 'おにいさんがくる',
    exampleRomaji: 'oniisan ga kuru',
    exampleKorean: '형이 온다'
  },
  {
    kanji: 'お姉さん',
    hiragana: 'おねえさん',
    romaji: 'oneesan',
    korean: '언니',
    english: '(honorable) older sister',
    partOfSpeech: 'noun',
    example: 'お姉さんと話す',
    exampleHiragana: 'おねえさんとはなす',
    exampleRomaji: 'oneesan to hanasu',
    exampleKorean: '언니와 이야기하다'
  },
  {
    kanji: 'お祖母さん',
    hiragana: 'おばあさん',
    romaji: 'obaasan',
    korean: '할머니',
    english: 'grandmother, female senior',
    partOfSpeech: 'noun',
    example: 'おばあさんが来た',
    exampleHiragana: 'おばあさんがきた',
    exampleRomaji: 'obaasan ga kita',
    exampleKorean: '할머니가 오셨다'
  },
  {
    kanji: '',
    hiragana: 'おばさん',
    romaji: 'obasan',
    korean: '아주머니',
    english: 'Aunt',
    partOfSpeech: 'noun',
    example: 'おばさんに会う',
    exampleHiragana: 'おばさんにあう',
    exampleRomaji: 'obasan ni au',
    exampleKorean: '아주머니를 만나다'
  },
  {
    kanji: 'お風呂',
    hiragana: 'おふろ',
    romaji: 'ofuro',
    korean: '목욕',
    english: 'Bath',
    partOfSpeech: 'noun',
    example: 'お風呂に入る',
    exampleHiragana: 'おふろにはいる',
    exampleRomaji: 'ofuro ni hairu',
    exampleKorean: '목욕을 하다'
  },
  {
    kanji: 'お弁当',
    hiragana: 'おべんとう',
    romaji: 'obentou',
    korean: '도시락',
    english: 'boxed lunch',
    partOfSpeech: 'noun',
    example: 'お弁当を作る',
    exampleHiragana: 'おべんとうをつくる',
    exampleRomaji: 'obentou o tsukuru',
    exampleKorean: '도시락을 만들다'
  },
  {
    kanji: '覚える',
    hiragana: 'おぼえる',
    romaji: 'oboeru',
    korean: '기억하다',
    english: 'to remember',
    partOfSpeech: 'verb',
    example: '単語を覚える',
    exampleHiragana: 'たんごをおぼえる',
    exampleRomaji: 'tango o oboeru',
    exampleKorean: '단어를 기억하다'
  },
  {
    kanji: '',
    hiragana: 'おまわりさん',
    romaji: 'omawarisan',
    korean: '경찰',
    english: 'friendly term for police',
    partOfSpeech: 'noun',
    example: 'おまわりさんに聞く',
    exampleHiragana: 'おまわりさんにきく',
    exampleRomaji: 'omawarisan ni kiku',
    exampleKorean: '경찰에게 물어보다'
  },
  {
    kanji: '重い',
    hiragana: 'おもい',
    romaji: 'omoi',
    korean: '무거운',
    english: 'Heavy',
    partOfSpeech: 'adjective',
    example: '重い荷物',
    exampleHiragana: 'おもいにもの',
    exampleRomaji: 'omoi nimotsu',
    exampleKorean: '무거운 짐'
  },
  {
    kanji: '',
    hiragana: 'おもしろい',
    romaji: 'omoshiroi',
    korean: '재미',
    english: 'Interesting',
    partOfSpeech: 'adjective',
    example: 'おもしろい本',
    exampleHiragana: 'おもしろいほん',
    exampleRomaji: 'omoshiroi hon',
    exampleKorean: '재미있는 책'
  },
  {
    kanji: '泳ぐ',
    hiragana: 'およぐ',
    romaji: 'oyogu',
    korean: '수영',
    english: 'to swim',
    partOfSpeech: 'verb',
    example: '海で泳ぐ',
    exampleHiragana: 'うみでおよぐ',
    exampleRomaji: 'umi de oyogu',
    exampleKorean: '바다에서 수영하다'
  },
  {
    kanji: '降りる',
    hiragana: 'おりる',
    romaji: 'oriru',
    korean: '내리다',
    english: 'to get off, to descend',
    partOfSpeech: 'verb',
    example: '電車を降りる',
    exampleHiragana: 'でんしゃをおりる',
    exampleRomaji: 'densha o oriru',
    exampleKorean: '전철에서 내리다'
  },
  {
    kanji: '終わる',
    hiragana: 'おわる',
    romaji: 'owaru',
    korean: '끝나다',
    english: 'to finish',
    partOfSpeech: 'verb',
    example: '授業が終わる',
    exampleHiragana: 'じゅぎょうがおわる',
    exampleRomaji: 'jugyou ga owaru',
    exampleKorean: '수업이 끝나다'
  },
  {
    kanji: '音楽',
    hiragana: 'おんがく',
    romaji: 'ongaku',
    korean: '음악',
    english: 'Music',
    partOfSpeech: 'noun',
    example: '音楽を聞く',
    exampleHiragana: 'おんがくをきく',
    exampleRomaji: 'ongaku o kiku',
    exampleKorean: '음악을 듣다'
  },
  {
    kanji: '女',
    hiragana: 'おんな',
    romaji: 'onna',
    korean: '여자',
    english: 'Woman',
    partOfSpeech: 'noun',
    example: '女の人が来た',
    exampleHiragana: 'おんなのひとがきた',
    exampleRomaji: 'onna no hito ga kita',
    exampleKorean: '여자가 왔다'
  },
  {
    kanji: '女の子',
    hiragana: 'おんなのこ',
    romaji: 'onna no ko',
    korean: '소녀',
    english: 'Girl',
    partOfSpeech: 'noun',
    example: '女の子が遊ぶ',
    exampleHiragana: 'おんなのこがあそぶ',
    exampleRomaji: 'onna no ko ga asobu',
    exampleKorean: '소녀가 놀다'
  },
  {
    kanji: '外国',
    hiragana: 'がいこく',
    romaji: 'gaikoku',
    korean: '외국',
    english: 'foreign country',
    partOfSpeech: 'noun',
    example: '外国に行く',
    exampleHiragana: 'がいこくにいく',
    exampleRomaji: 'gaikoku ni iku',
    exampleKorean: '외국에 가다'
  },
  {
    kanji: '外国人',
    hiragana: 'がいこくじん',
    romaji: 'gaikokujin',
    korean: '외국인',
    english: 'Foreigner',
    partOfSpeech: 'noun',
    example: '外国人が来た',
    exampleHiragana: 'がいこくじんがきた',
    exampleRomaji: 'gaikokujin ga kita',
    exampleKorean: '외국인이 왔다'
  },
  {
    kanji: '会社',
    hiragana: 'かいしゃ',
    romaji: 'kaisha',
    korean: '회사',
    english: 'Company',
    partOfSpeech: 'noun',
    example: '会社に行く',
    exampleHiragana: 'かいしゃにいく',
    exampleRomaji: 'kaisha ni iku',
    exampleKorean: '회사에 가다'
  },
  {
    kanji: '階段',
    hiragana: 'かいだん',
    romaji: 'kaidan',
    korean: '계단',
    english: 'Stairs',
    partOfSpeech: 'noun',
    example: '階段を上る',
    exampleHiragana: 'かいだんをのぼる',
    exampleRomaji: 'kaidan o noboru',
    exampleKorean: '계단을 오르다'
  },
  {
    kanji: '買い物',
    hiragana: 'かいもの',
    romaji: 'kaimono',
    korean: '쇼핑',
    english: 'Shopping',
    partOfSpeech: 'noun',
    example: '買い物に行く',
    exampleHiragana: 'かいものにいく',
    exampleRomaji: 'kaimono ni iku',
    exampleKorean: '쇼핑하러 가다'
  },
  {
    kanji: '買う',
    hiragana: 'かう',
    romaji: 'kau',
    korean: '구매',
    english: 'to buy',
    partOfSpeech: 'verb',
    example: '本を買う',
    exampleHiragana: 'ほんをかう',
    exampleRomaji: 'hon o kau',
    exampleKorean: '책을 사다'
  },
  {
    kanji: '返す',
    hiragana: 'かえす',
    romaji: 'kaesu',
    korean: '반환하다',
    english: 'to return something',
    partOfSpeech: 'verb',
    example: '本を返す',
    exampleHiragana: 'ほんをかえす',
    exampleRomaji: 'hon o kaesu',
    exampleKorean: '책을 반환하다'
  },
  {
    kanji: '帰る',
    hiragana: 'かえる',
    romaji: 'kaeru',
    korean: '돌아',
    english: 'to go back',
    partOfSpeech: 'verb',
    example: '家に帰る',
    exampleHiragana: 'いえにかえる',
    exampleRomaji: 'ie ni kaeru',
    exampleKorean: '집에 돌아가다'
  },
  {
    kanji: '',
    hiragana: 'かかる',
    romaji: 'kakaru',
    korean: '걸리다',
    english: 'to take time or money',
    partOfSpeech: 'verb',
    example: '時間がかかる',
    exampleHiragana: 'じかんがかかる',
    exampleRomaji: 'jikan ga kakaru',
    exampleKorean: '시간이 걸리다'
  },
  {
    kanji: '',
    hiragana: 'かぎ',
    romaji: 'kagi',
    korean: '열쇠',
    english: 'Key',
    partOfSpeech: 'noun',
    example: 'かぎを忘れる',
    exampleHiragana: 'かぎをわすれる',
    exampleRomaji: 'kagi o wasureru',
    exampleKorean: '열쇠를 잊다'
  },
  {
    kanji: '書く',
    hiragana: 'かく',
    romaji: 'kaku',
    korean: '쓰기',
    english: 'to write',
    partOfSpeech: 'verb',
    example: '手紙を書く',
    exampleHiragana: 'てがみをかく',
    exampleRomaji: 'tegami o kaku',
    exampleKorean: '편지를 쓰다'
  },
  {
    kanji: '学生',
    hiragana: 'がくせい',
    romaji: 'gakusei',
    korean: '학생',
    english: 'Student',
    partOfSpeech: 'noun',
    example: '学生が勉強する',
    exampleHiragana: 'がくせいがべんきょうする',
    exampleRomaji: 'gakusei ga benkyou suru',
    exampleKorean: '학생이 공부하다'
  },
  {
    kanji: '',
    hiragana: 'かける',
    romaji: 'kakeru',
    korean: '걸다',
    english: 'to call by phone',
    partOfSpeech: 'verb',
    example: '電話をかける',
    exampleHiragana: 'でんわをかける',
    exampleRomaji: 'denwa o kakeru',
    exampleKorean: '전화를 걸다'
  },
  {
    kanji: '傘',
    hiragana: 'かさ',
    romaji: 'kasa',
    korean: '우산',
    english: 'Umbrella',
    partOfSpeech: 'noun',
    example: '傘をさす',
    exampleHiragana: 'かさをさす',
    exampleRomaji: 'kasa o sasu',
    exampleKorean: '우산을 쓰다'
  },
  {
    kanji: '貸す',
    hiragana: 'かす',
    romaji: 'kasu',
    korean: '빌려',
    english: 'to lend',
    partOfSpeech: 'verb',
    example: '本を貸す',
    exampleHiragana: 'ほんをかす',
    exampleRomaji: 'hon o kasu',
    exampleKorean: '책을 빌려주다'
  },
  {
    kanji: '風',
    hiragana: 'かぜ',
    romaji: 'kaze',
    korean: '바람',
    english: 'Wind',
    partOfSpeech: 'noun',
    example: '風が強い',
    exampleHiragana: 'かぜがつよい',
    exampleRomaji: 'kaze ga tsuyoi',
    exampleKorean: '바람이 세다'
  },
  {
    kanji: '風邪',
    hiragana: 'かぜ',
    romaji: 'kaze',
    korean: '감기',
    english: 'a cold',
    partOfSpeech: 'noun',
    example: '風邪をひく',
    exampleHiragana: 'かぜをひく',
    exampleRomaji: 'kaze o hiku',
    exampleKorean: '감기에 걸리다'
  },
  {
    kanji: '家族',
    hiragana: 'かぞく',
    romaji: 'kazoku',
    korean: '가족',
    english: 'Family',
    partOfSpeech: 'noun',
    example: '家族と一緒に',
    exampleHiragana: 'かぞくといっしょに',
    exampleRomaji: 'kazoku to issho ni',
    exampleKorean: '가족과 함께'
  },
  {
    kanji: '方',
    hiragana: 'かた',
    romaji: 'kata',
    korean: '방법',
    english: 'person, way of doing',
    partOfSpeech: 'noun',
    example: 'この方',
    exampleHiragana: 'このかた',
    exampleRomaji: 'kono kata',
    exampleKorean: '이 분'
  },
  {
    kanji: '学校',
    hiragana: 'がっこう',
    romaji: 'gakkou',
    korean: '학교',
    english: 'School',
    partOfSpeech: 'noun',
    example: '学校に行く',
    exampleHiragana: 'がっこうにいく',
    exampleRomaji: 'gakkou ni iku',
    exampleKorean: '학교에 가다'
  },
  {
    kanji: '',
    hiragana: 'カップ',
    romaji: 'kappu',
    korean: '컵',
    english: 'Cup',
    partOfSpeech: 'noun',
    example: 'カップにコーヒーを入れる',
    exampleHiragana: 'かっぷにこーひーをいれる',
    exampleRomaji: 'kappu ni koohii o ireru',
    exampleKorean: '컵에 커피를 넣다'
  },
  {
    kanji: '家庭',
    hiragana: 'かてい',
    romaji: 'katei',
    korean: '가정',
    english: 'Household',
    partOfSpeech: 'noun',
    example: '家庭の事情',
    exampleHiragana: 'かていのじじょう',
    exampleRomaji: 'katei no jijou',
    exampleKorean: '가정 사정'
  },
  {
    kanji: '角',
    hiragana: 'かど',
    romaji: 'kado',
    korean: '모서리',
    english: 'a corner',
    partOfSpeech: 'noun',
    example: '角を曲がる',
    exampleHiragana: 'かどをまがる',
    exampleRomaji: 'kado o magaru',
    exampleKorean: '모퉁이를 돌다'
  },
  {
    kanji: '',
    hiragana: 'かばん',
    romaji: 'kaban',
    korean: '가방',
    english: 'bag, basket',
    partOfSpeech: 'noun',
    example: 'かばんを持つ',
    exampleHiragana: 'かばんをもつ',
    exampleRomaji: 'kaban o motsu',
    exampleKorean: '가방을 들다'
  },
  {
    kanji: '花瓶',
    hiragana: 'かぴん',
    romaji: 'kabin',
    korean: '꽃병',
    english: 'a vase',
    partOfSpeech: 'noun',
    example: '花瓶に花を入れる',
    exampleHiragana: 'かぴんにはなをいれる',
    exampleRomaji: 'kabin ni hana o ireru',
    exampleKorean: '꽃병에 꽃을 넣다'
  },
  {
    kanji: '紙',
    hiragana: 'かみ',
    romaji: 'kami',
    korean: '종이',
    english: 'paper',
    partOfSpeech: 'noun',
    example: '紙に書く',
    exampleHiragana: 'かみにかく',
    exampleRomaji: 'kami ni kaku',
    exampleKorean: '종이에 쓰다'
  },
  {
    kanji: '',
    hiragana: 'カメラ',
    romaji: 'kamera',
    korean: '카메라',
    english: 'camera',
    partOfSpeech: 'noun',
    example: 'カメラで写真を撮る',
    exampleHiragana: 'かめらでしゃしんをとる',
    exampleRomaji: 'kamera de shashin o toru',
    exampleKorean: '카메라로 사진을 찍다'
  },
  {
    kanji: '火曜日',
    hiragana: 'かようび',
    romaji: 'kayoubi',
    korean: '화요일',
    english: 'Tuesday',
    partOfSpeech: 'noun',
    example: '火曜日に会う',
    exampleHiragana: 'かようびにあう',
    exampleRomaji: 'kayoubi ni au',
    exampleKorean: '화요일에 만나다'
  },
  {
    kanji: '辛い',
    hiragana: 'からい',
    romaji: 'karai',
    korean: '맵다',
    english: 'Spicy',
    partOfSpeech: 'adjective',
    example: '辛い料理',
    exampleHiragana: 'からいりょうり',
    exampleRomaji: 'karai ryouri',
    exampleKorean: '매운 요리'
  },
  {
    kanji: '体',
    hiragana: 'からだ',
    romaji: 'karada',
    korean: '몸',
    english: 'Body',
    partOfSpeech: 'noun',
    example: '体を動かす',
    exampleHiragana: 'からだをうごかす',
    exampleRomaji: 'karada o ugokasu',
    exampleKorean: '몸을 움직이다'
  },
  {
    kanji: '借りる',
    hiragana: 'かりる',
    romaji: 'kariru',
    korean: '빌리다',
    english: 'to borrow',
    partOfSpeech: 'verb',
    example: '本を借りる',
    exampleHiragana: 'ほんをかりる',
    exampleRomaji: 'hon o kariru',
    exampleKorean: '책을 빌리다'
  },
  {
    kanji: '軽い',
    hiragana: 'かるい',
    romaji: 'karui',
    korean: '가볍다',
    english: 'Light',
    partOfSpeech: 'adjective',
    example: '軽い荷物',
    exampleHiragana: 'かるいにもの',
    exampleRomaji: 'karui nimotsu',
    exampleKorean: '가벼운 짐'
  },
  {
    kanji: '',
    hiragana: 'カレー',
    romaji: 'karee',
    korean: '카레',
    english: 'Curry',
    partOfSpeech: 'noun',
    example: 'カレーを食べる',
    exampleHiragana: 'かれーをたべる',
    exampleRomaji: 'karee o taberu',
    exampleKorean: '카레를 먹다'
  },
  {
    kanji: '',
    hiragana: 'カレンダー',
    romaji: 'karendaa',
    korean: '달력',
    english: 'calendar',
    partOfSpeech: 'noun',
    example: 'カレンダーを見る',
    exampleHiragana: 'かれんだーをみる',
    exampleRomaji: 'karendaa o miru',
    exampleKorean: '달력을 보다'
  },
  {
    kanji: '川/河',
    hiragana: 'かわ',
    romaji: 'kawa',
    korean: '강',
    english: 'River',
    partOfSpeech: 'noun',
    example: '川を渡る',
    exampleHiragana: 'かわをわたる',
    exampleRomaji: 'kawa o wataru',
    exampleKorean: '강을 건너다'
  },
  {
    kanji: '',
    hiragana: 'かわいい',
    romaji: 'kawaii',
    korean: '귀엽다',
    english: 'Cute',
    partOfSpeech: 'adjective',
    example: 'かわいい子',
    exampleHiragana: 'かわいいこ',
    exampleRomaji: 'kawaii ko',
    exampleKorean: '귀여운 아이'
  },
  {
    kanji: '漢字',
    hiragana: 'かんじ',
    romaji: 'kanji',
    korean: '한자',
    english: 'Chinese character',
    partOfSpeech: 'noun',
    example: '漢字を覚える',
    exampleHiragana: 'かんじをおぼえる',
    exampleRomaji: 'kanji o oboeru',
    exampleKorean: '한자를 기억하다'
  },
  {
    kanji: '木',
    hiragana: 'き',
    romaji: 'ki',
    korean: '나무',
    english: 'tree, wood',
    partOfSpeech: 'noun',
    example: '木の下',
    exampleHiragana: 'きのした',
    exampleRomaji: 'ki no shita',
    exampleKorean: '나무 아래'
  },
  {
    kanji: '黄色い',
    hiragana: 'きいろい',
    romaji: 'kiiroi',
    korean: '노랗다',
    english: 'yellow',
    partOfSpeech: 'adjective',
    example: '黄色い花',
    exampleHiragana: 'きいろいはな',
    exampleRomaji: 'kiiroi hana',
    exampleKorean: '노란 꽃'
  },
  {
    kanji: '消える',
    hiragana: 'きえる',
    romaji: 'kieru',
    korean: '사라',
    english: 'to disappear',
    partOfSpeech: 'verb',
    example: '光が消える',
    exampleHiragana: 'ひかりがきえる',
    exampleRomaji: 'hikari ga kieru',
    exampleKorean: '빛이 사라지다'
  },
  {
    kanji: '聞く',
    hiragana: 'きく',
    romaji: 'kiku',
    korean: '듣다',
    english: 'to hear, to listen to',
    partOfSpeech: 'verb',
    example: '音楽を聞く',
    exampleHiragana: 'おんがくをきく',
    exampleRomaji: 'ongaku o kiku',
    exampleKorean: '음악을 듣다'
  },
  {
    kanji: '北',
    hiragana: 'きた',
    romaji: 'kita',
    korean: '북',
    english: 'North',
    partOfSpeech: 'noun',
    example: '北の方へ',
    exampleHiragana: 'きたのほうへ',
    exampleRomaji: 'kita no hou e',
    exampleKorean: '북쪽으로'
  },
  {
    kanji: '',
    hiragana: 'ギター',
    romaji: 'gitaa',
    korean: '기타',
    english: 'Guitar',
    partOfSpeech: 'noun',
    example: 'ギターを弾く',
    exampleHiragana: 'ぎたーをひく',
    exampleRomaji: 'gitaa o hiku',
    exampleKorean: '기타를 치다'
  },
  {
    kanji: '汚い',
    hiragana: 'きたない',
    romaji: 'kitanai',
    korean: '더러운',
    english: 'Dirty',
    partOfSpeech: 'adjective',
    example: '汚い部屋',
    exampleHiragana: 'きたないへや',
    exampleRomaji: 'kitanai heya',
    exampleKorean: '더러운 방'
  },
  {
    kanji: '喫茶店',
    hiragana: 'きっさてん',
    romaji: 'kissaten',
    korean: '커피숍',
    english: 'coffee lounge',
    partOfSpeech: 'noun',
    example: '喫茶店でコーヒーを飲む',
    exampleHiragana: 'きっさてんでこーひーをのむ',
    exampleRomaji: 'kissaten de koohii o nomu',
    exampleKorean: '커피숍에서 커피를 마시다'
  },
  {
    kanji: '切手',
    hiragana: 'きって',
    romaji: 'kitte',
    korean: '우표',
    english: 'postage stamp',
    partOfSpeech: 'noun',
    example: '切手を貼る',
    exampleHiragana: 'きってをはる',
    exampleRomaji: 'kitte o haru',
    exampleKorean: '우표를 붙이다'
  },
  {
    kanji: '切符',
    hiragana: 'きっぷ',
    romaji: 'kippu',
    korean: '티켓',
    english: 'Ticket',
    partOfSpeech: 'noun',
    example: '切符を買う',
    exampleHiragana: 'きっぷをかう',
    exampleRomaji: 'kippu o kau',
    exampleKorean: '표를 사다'
  },
  {
    kanji: '昨日',
    hiragana: 'きのう',
    romaji: 'kinou',
    korean: '어제',
    english: 'Yesterday',
    partOfSpeech: 'noun',
    example: '昨日会った',
    exampleHiragana: 'きのうあった',
    exampleRomaji: 'kinou atta',
    exampleKorean: '어제 만났다'
  },
  {
    kanji: '九',
    hiragana: 'きゅう',
    romaji: 'kyuu',
    korean: '아홉',
    english: 'Nine',
    partOfSpeech: 'number',
    example: '九時',
    exampleHiragana: 'きゅうじ',
    exampleRomaji: 'kyuu ji',
    exampleKorean: '아홉 시'
  },
  {
    kanji: '牛肉',
    hiragana: 'ぎゅうにく',
    romaji: 'gyuuniku',
    korean: '쇠고기',
    english: 'Beef',
    partOfSpeech: 'noun',
    example: '牛肉を食べる',
    exampleHiragana: 'ぎゅうにくをたべる',
    exampleRomaji: 'gyuuniku o taberu',
    exampleKorean: '쇠고기를 먹다'
  },
  {
    kanji: '牛乳',
    hiragana: 'ぎゅうにゅう',
    romaji: 'gyuunyuu',
    korean: '우유',
    english: 'Milk',
    partOfSpeech: 'noun',
    example: '牛乳を飲む',
    exampleHiragana: 'ぎゅうにゅうをのむ',
    exampleRomaji: 'gyuunyuu o nomu',
    exampleKorean: '우유를 마시다'
  },
  {
    kanji: '今日',
    hiragana: 'きょう',
    romaji: 'kyou',
    korean: '오늘',
    english: 'Today',
    partOfSpeech: 'noun',
    example: '今日は暑い',
    exampleHiragana: 'きょうはあつい',
    exampleRomaji: 'kyou wa atsui',
    exampleKorean: '오늘은 덥다'
  },
  {
    kanji: '教室',
    hiragana: 'きょうしつ',
    romaji: 'kyoushitsu',
    korean: '교실',
    english: 'Classroom',
    partOfSpeech: 'noun',
    example: '教室に入る',
    exampleHiragana: 'きょうしつにはいる',
    exampleRomaji: 'kyoushitsu ni hairu',
    exampleKorean: '교실에 들어가다'
  },
  {
    kanji: '兄弟',
    hiragana: 'きょうだい',
    romaji: 'kyoudai',
    korean: '형제',
    english: '(humble) siblings',
    partOfSpeech: 'noun',
    example: '兄弟がいる',
    exampleHiragana: 'きょうだいがいる',
    exampleRomaji: 'kyoudai ga iru',
    exampleKorean: '형제가 있다'
  },
  {
    kanji: '去年',
    hiragana: 'きょねん',
    romaji: 'kyonen',
    korean: '작년',
    english: 'last year',
    partOfSpeech: 'noun',
    example: '去年日本に行った',
    exampleHiragana: 'きょねんにほんにいった',
    exampleRomaji: 'kyonen nihon ni itta',
    exampleKorean: '작년 일본에 갔다'
  },
  {
    kanji: '嫌い',
    hiragana: 'きらい',
    romaji: 'kirai',
    korean: '싫음',
    english: 'Hate',
    partOfSpeech: 'adjective',
    example: '嫌いな食べ物',
    exampleHiragana: 'きらいなたべもの',
    exampleRomaji: 'kirai na tabemono',
    exampleKorean: '싫어하는 음식'
  },
  {
    kanji: '切る',
    hiragana: 'きる',
    romaji: 'kiru',
    korean: '자르다',
    english: 'to cut',
    partOfSpeech: 'verb',
    example: '紙を切る',
    exampleHiragana: 'かみをきる',
    exampleRomaji: 'kami o kiru',
    exampleKorean: '종이를 자르다'
  },
  {
    kanji: '着る',
    hiragana: 'きる',
    romaji: 'kiru',
    korean: '옷을 입다',
    english: 'to put on from the shoulders',
    partOfSpeech: 'verb',
    example: '服を着る',
    exampleHiragana: 'ふくをきる',
    exampleRomaji: 'fuku o kiru',
    exampleKorean: '옷을 입다'
  },
  {
    kanji: '',
    hiragana: 'きれい',
    romaji: 'kirei',
    korean: '예쁨',
    english: 'pretty, clean',
    partOfSpeech: 'adjective',
    example: 'きれいな花',
    exampleHiragana: 'きれいなはな',
    exampleRomaji: 'kirei na hana',
    exampleKorean: '예쁜 꽃'
  },
  {
    kanji: '',
    hiragana: 'キロ',
    romaji: 'kiro',
    korean: '킬로그램',
    english: 'Kilogram',
    partOfSpeech: 'noun',
    example: '三キロ',
    exampleHiragana: 'さんきろ',
    exampleRomaji: 'san kiro',
    exampleKorean: '삼 킬로그램'
  },
  {
    kanji: '',
    hiragana: 'キロ',
    romaji: 'kiro',
    korean: '킬로미터',
    english: 'Kilometer',
    partOfSpeech: 'noun',
    example: '五キロ',
    exampleHiragana: 'ごきろ',
    exampleRomaji: 'go kiro',
    exampleKorean: '오 킬로미터'
  },
  {
    kanji: '銀行',
    hiragana: 'ぎんこう',
    romaji: 'ginkou',
    korean: '은행',
    english: 'Bank',
    partOfSpeech: 'noun',
    example: '銀行に行く',
    exampleHiragana: 'ぎんこうにいく',
    exampleRomaji: 'ginkou ni iku',
    exampleKorean: '은행에 가다'
  },
  {
    kanji: '金曜日',
    hiragana: 'きんようび',
    romaji: 'kin youbi',
    korean: '금요일',
    english: 'Friday',
    partOfSpeech: 'noun',
    example: '金曜日に会う',
    exampleHiragana: 'きんようびにあう',
    exampleRomaji: 'kin youbi ni au',
    exampleKorean: '금요일에 만나다'
  },
  {
    kanji: '薬',
    hiragana: 'くすり',
    romaji: 'kusuri',
    korean: '약',
    english: 'medicine',
    partOfSpeech: 'noun',
    example: '薬を飲む',
    exampleHiragana: 'くすりをのむ',
    exampleRomaji: 'kusuri o nomu',
    exampleKorean: '약을 먹다'
  }
]

// 배열을 랜덤하게 섞는 함수
export const shuffleArray = (array) => {
  const shuffled = [...array]
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]]
  }
  return shuffled
}

